import type { Program } from "./programs";

type Row = [string, string, string, number, Program["level"], string, string];

// Additional catalog entries. These are discovery/SEO entries; exact prescriptions for named programs should be checked against the current author/source.
const rows: Row[] = [
  ["531-fsl", "5/3/1 First Set Last", "Strength", 4, "Intermediate", "Strength", "Barbell gym"],
  ["531-building-the-monolith", "5/3/1 Building the Monolith", "Strength", 3, "Advanced", "Strength and size", "Barbell gym"],
  ["531-krypteia", "5/3/1 Krypteia", "Strength", 3, "Intermediate", "Strength and conditioning", "Barbell gym"],
  ["531-god-is-a-beast", "5/3/1 God Is A Beast", "Strength", 4, "Intermediate", "Strength and work capacity", "Barbell gym"],
  ["531-forever", "5/3/1 Forever", "Strength", 4, "Intermediate", "Long-term strength", "Barbell gym"],
  ["gzcl-uhf", "GZCL UHF", "Strength", 5, "Intermediate", "Strength and hypertrophy", "Barbell gym"],
  ["gzcl-rippler", "GZCL The Rippler", "Strength", 4, "Intermediate", "Strength and muscle", "Barbell gym"],
  ["gzcl-general-gainz", "GZCL General Gainz", "Strength", 4, "Intermediate", "Strength and autoregulation", "Barbell gym"],
  ["greg-nuckols-3x-week", "Greg Nuckols 3x Weekly Strength", "Strength", 3, "Intermediate", "Strength", "Barbell gym"],
  ["greg-nuckols-28-bench", "Greg Nuckols 28 Programs: Bench", "Powerlifting", 3, "Intermediate", "Bench strength", "Barbell gym"],
  ["greg-nuckols-28-squat", "Greg Nuckols 28 Programs: Squat", "Powerlifting", 3, "Intermediate", "Squat strength", "Barbell gym"],
  ["greg-nuckols-28-deadlift", "Greg Nuckols 28 Programs: Deadlift", "Powerlifting", 3, "Intermediate", "Deadlift strength", "Barbell gym"],
  ["sbs-novice-strength", "Stronger By Science Novice Program", "Strength", 3, "Beginner", "Strength", "Barbell gym"],
  ["sbs-average-to-savage", "Stronger By Science Average To Savage", "Strength", 4, "Intermediate", "Strength and hypertrophy", "Barbell gym"],
  ["sbs-hypertrophy", "Stronger By Science Hypertrophy Program", "Hypertrophy", 4, "Intermediate", "Muscle building", "Full gym"],
  ["tsa-intermediate", "The Strength Athlete Intermediate", "Powerlifting", 4, "Intermediate", "Powerlifting strength", "Barbell gym"],
  ["tsa-9-week", "The Strength Athlete 9-Week Program", "Powerlifting", 4, "Intermediate", "Competition strength", "Barbell gym"],
  ["calgary-barbell-16-week", "Calgary Barbell 16-Week Program", "Powerlifting", 4, "Intermediate", "Powerlifting strength", "Barbell gym"],
  ["calgary-barbell-8-week", "Calgary Barbell 8-Week Program", "Powerlifting", 4, "Intermediate", "Powerlifting strength", "Barbell gym"],
  ["bryce-lewis-strength", "Bryce Lewis Strength Program", "Powerlifting", 4, "Intermediate", "Powerlifting strength", "Barbell gym"],
  ["sheiko-29", "Sheiko #29", "Powerlifting", 4, "Intermediate", "Powerlifting technique and volume", "Barbell gym"],
  ["sheiko-30", "Sheiko #30", "Powerlifting", 4, "Intermediate", "Powerlifting technique and volume", "Barbell gym"],
  ["sheiko-31", "Sheiko #31", "Powerlifting", 4, "Intermediate", "Powerlifting technique and volume", "Barbell gym"],
  ["sheiko-32", "Sheiko #32", "Powerlifting", 4, "Intermediate", "Powerlifting technique and volume", "Barbell gym"],
  ["bill-starr-5x5", "Bill Starr 5×5", "Strength", 3, "Intermediate", "Strength", "Barbell gym"],
  ["reg-park-5x5", "Reg Park 5×5", "Strength", 3, "Intermediate", "Strength and muscle", "Barbell gym"],
  ["stronger-by-science-rir", "Stronger By Science RIR Program", "Hypertrophy", 4, "Intermediate", "Muscle building and autoregulation", "Full gym"],
  ["dc-training", "Doggcrapp Training", "Bodybuilding", 3, "Advanced", "Muscle building and strength", "Full gym"],
  ["fst-7", "FST-7 Training", "Bodybuilding", 5, "Intermediate", "Muscle building", "Full gym"],
  ["mentzer-heavy-duty", "Mike Mentzer Heavy Duty", "Bodybuilding", 3, "Advanced", "High-intensity muscle building", "Full gym"],
  ["dorian-yates-blood-and-guts-2", "Dorian Yates Blood & Guts 2", "Bodybuilding", 4, "Advanced", "Muscle building", "Full gym"],
  ["victor-richards-volume", "High-Volume Bodybuilding Template", "Bodybuilding", 5, "Advanced", "Muscle building", "Full gym"],
  ["strong-curves", "Strong Curves", "Hypertrophy", 3, "Beginner", "Strength and muscle", "Full gym"],
  ["thinner-leaner-stronger", "Thinner Leaner Stronger", "Hypertrophy", 3, "Beginner", "Strength and muscle", "Full gym"],
  ["new-rules-of-lifting", "The New Rules of Lifting", "General Fitness", 3, "Beginner", "Strength and fitness", "Full gym"],
  ["female-bodybuilding-upper-lower", "Women’s Upper / Lower Strength & Hypertrophy", "Hypertrophy", 4, "All Levels", "Muscle and strength", "Full gym"],
  ["female-full-body-3-day", "Women’s Full Body 3-Day", "Hypertrophy", 3, "All Levels", "Strength and muscle", "Full gym"],
  ["hatch-squat", "Hatch Squat Program", "Olympic Weightlifting", 3, "Intermediate", "Squat strength", "Barbell gym"],
  ["bulgarian-method", "Bulgarian Method", "Olympic Weightlifting", 6, "Advanced", "Weightlifting strength", "Barbell gym"],
  ["cal-strength-weightlifting", "Catalyst Athletics Strength Cycle", "Olympic Weightlifting", 4, "Intermediate", "Olympic lifting strength", "Barbell gym"],
  ["snatch-specialization", "Snatch Specialization Program", "Olympic Weightlifting", 4, "Intermediate", "Snatch technique and strength", "Barbell gym"],
  ["clean-jerk-specialization", "Clean & Jerk Specialization Program", "Olympic Weightlifting", 4, "Intermediate", "Clean and jerk technique", "Barbell gym"],
  ["kettlebell-rite-of-passage", "Kettlebell Rite of Passage", "Kettlebell", 4, "Intermediate", "Kettlebell strength and conditioning", "Kettlebell"],
  ["enter-the-kettlebell", "Enter the Kettlebell", "Kettlebell", 3, "Beginner", "Kettlebell strength", "Kettlebell"],
  ["dry-fighting-weight", "Dry Fighting Weight", "Kettlebell", 4, "Intermediate", "Kettlebell strength and conditioning", "Kettlebell"],
  ["kettlebell-simple-strength", "Kettlebell Simple Strength", "Kettlebell", 3, "All Levels", "Strength and conditioning", "Kettlebell"],
  ["recommended-routine", "Bodyweight Recommended Routine", "Calisthenics", 3, "All Levels", "Relative strength", "Bodyweight / bars"],
  ["convict-conditioning", "Convict Conditioning", "Calisthenics", 3, "Beginner", "Bodyweight strength", "Bodyweight"],
  ["hybrid-calisthenics", "Hybrid Calisthenics Program", "Calisthenics", 3, "Beginner", "Bodyweight strength", "Bodyweight"],
  ["calisthenics-push-pull-legs", "Calisthenics Push Pull Legs", "Calisthenics", 6, "Intermediate", "Relative strength and muscle", "Bodyweight / bars"],
  ["grease-the-groove-pullups", "Grease the Groove Pull-Up Program", "Calisthenics", 5, "Beginner", "Pull-up strength", "Bodyweight / bar"],
  ["murph-prep", "Murph Preparation Program", "Conditioning", 4, "Intermediate", "Work capacity and calisthenics", "Bodyweight / running"],
  ["cindy-prep", "Cindy Preparation Program", "Conditioning", 3, "Beginner", "Conditioning and bodyweight fitness", "Bodyweight / bar"],
  ["hyrox-8-week", "HYROX 8-Week Training Program", "Conditioning", 5, "Intermediate", "Hybrid endurance and strength", "Full gym"],
  ["hybrid-strength-running", "Hybrid Strength & Running 4-Day", "Conditioning", 4, "Intermediate", "Strength and endurance", "Full gym"],
  ["couch-to-5k", "Couch to 5K", "Conditioning", 3, "Beginner", "Running fitness", "Minimal equipment"],
  ["5k-strength-support", "5K Strength Support Program", "Conditioning", 3, "All Levels", "Running support and strength", "Full gym"],
  ["athlete-in-season", "In-Season Athlete Strength Program", "Conditioning", 3, "Intermediate", "Strength maintenance and performance", "Full gym"],
  ["off-season-athlete", "Off-Season Athlete Strength Program", "Conditioning", 4, "Intermediate", "Strength and athletic development", "Full gym"],
  ["general-strength-3-day", "General Strength 3-Day", "Strength", 3, "All Levels", "General strength", "Full gym"],
  ["general-strength-4-day", "General Strength 4-Day", "Strength", 4, "All Levels", "General strength", "Full gym"],
  ["intermediate-full-body-3", "Intermediate Full Body 3-Day", "Strength", 3, "Intermediate", "Strength and muscle", "Full gym"],
  ["intermediate-upper-lower-4", "Intermediate Upper / Lower 4-Day", "Hypertrophy", 4, "Intermediate", "Muscle and strength", "Full gym"],
  ["advanced-upper-lower-5", "Advanced Upper / Lower 5-Day", "Hypertrophy", 5, "Advanced", "Muscle building", "Full gym"],
  ["6-day-push-pull-legs-strength", "6-Day Push Pull Legs Strength", "Powerbuilding", 6, "Advanced", "Strength and muscle", "Full gym"],
  ["powerbuilding-upper-lower-4", "Powerbuilding Upper / Lower 4-Day", "Powerbuilding", 4, "Intermediate", "Strength and size", "Full gym"],
  ["powerbuilding-ppl-5", "Powerbuilding PPL 5-Day", "Powerbuilding", 5, "Intermediate", "Strength and size", "Full gym"],
  ["minimalist-barbell-2-day", "Minimalist Barbell 2-Day", "Strength", 2, "All Levels", "Efficient strength", "Barbell gym"],
  ["full-body-dumbbell-4-day", "Dumbbell Full Body 4-Day", "Home & Bodyweight", 4, "All Levels", "Strength and muscle", "Dumbbells"],
  ["home-kettlebell-3-day", "Home Kettlebell 3-Day", "Kettlebell", 3, "All Levels", "Strength and conditioning", "Kettlebell"],
  ["home-bodyweight-5-day", "Home Bodyweight 5-Day", "Home & Bodyweight", 5, "Intermediate", "Muscle and conditioning", "Bodyweight"],
  ["hotel-gym-full-body", "Hotel Gym Full Body Program", "General Fitness", 3, "All Levels", "Strength and fitness", "Hotel gym / dumbbells"],
  ["busy-professional-3-day", "Busy Professional 3-Day Program", "General Fitness", 3, "All Levels", "Efficient strength and fitness", "Full gym"],
  ["30-minute-upper-lower", "30-Minute Upper / Lower", "General Fitness", 4, "All Levels", "Efficient strength and muscle", "Full gym"],
  ["deload-strength-week", "Strength Deload Week Template", "Strength", 3, "All Levels", "Fatigue management and consistency", "Full gym"],
];

const desc = (r: Row) => `${r[1]} is a ${r[3]}-day ${r[2].toLowerCase()} training approach focused on ${r[5].toLowerCase()}. Use this page to understand the training style and organize your workouts in Gym Log.`;
const structure = (r: Row) => r[2] === "Strength" || r[2] === "Powerlifting" ? ["Primary strength movements", "Supplemental work", "Accessory exercises", "Progressive loading"] : r[2] === "Hypertrophy" || r[2] === "Bodybuilding" || r[2] === "Powerbuilding" ? ["Main movement patterns", "Hypertrophy-focused work", "Accessory exercises", "Manage weekly volume"] : r[2] === "Olympic Weightlifting" ? ["Technical lifts", "Strength development", "Squat or pull variations", "Manage recovery"] : r[2] === "Kettlebell" || r[2] === "Calisthenics" ? ["Primary skill or movement", "Strength work", "Accessory or progression work", "Progress gradually"] : ["Strength or conditioning work", "Supporting exercises", "Progress gradually", "Adjust around recovery"];

export const EXTRA_PROGRAMS_2: Program[] = rows.map(r => ({
  slug: r[0], name: r[1], category: r[2], days: r[3], level: r[4], goal: r[5], equipment: r[6],
  description: desc(r),
  bestFor: `People seeking a structured ${r[2].toLowerCase()} routine with a clear weekly schedule.`,
  structure: structure(r),
  notes: "This page is an informational overview. For named programs, use the current author or official source for exact prescriptions. Gym Log helps you organize and track the routine you choose."
}));
