import type { Program } from "./programs";

type Row = [string, string, string, number, Program["level"], string, string];

// Discovery entries for high-value training categories. For named programs, verify
// the current author/source for exact prescriptions; Gym Log provides the tracking layer.
const rows: Row[] = [
  ["barbell-medicine-beginner","Barbell Medicine Beginner Prescription","Strength",3,"Beginner","Strength and general fitness","Barbell gym"],
  ["barbell-medicine-bridge","Barbell Medicine The Bridge","Strength",3,"Intermediate","Strength and general fitness","Barbell gym"],
  ["barbell-medicine-powerbuilding","Barbell Medicine Powerbuilding","Powerbuilding",4,"Intermediate","Strength and muscle","Full gym"],
  ["barbell-medicine-hypertrophy","Barbell Medicine Hypertrophy","Hypertrophy",4,"Intermediate","Muscle building","Full gym"],
  ["531-beyond","5/3/1 Beyond","Strength",4,"Intermediate","Long-term strength","Barbell gym"],
  ["531-leviathan","5/3/1 Leviathan","Strength",4,"Advanced","Strength and size","Barbell gym"],
  ["531-boring-but-big-3-day","5/3/1 Boring But Big 3-Day","Powerbuilding",3,"Intermediate","Strength and size","Barbell gym"],
  ["531-planning-templates","5/3/1 Planning Template","Strength",4,"Intermediate","Strength and consistency","Barbell gym"],
  ["gzcl-tulp","GZCL TULP","Strength",4,"Intermediate","Strength and hypertrophy","Barbell gym"],
  ["gzcl-the-rippler-3-day","GZCL The Rippler 3-Day","Strength",3,"Intermediate","Strength and muscle","Barbell gym"],
  ["gzcl-ultra-high-frequency","GZCL Ultra High Frequency","Strength",6,"Advanced","Strength and hypertrophy","Barbell gym"],
  ["stronger-by-science-2x-week","Stronger By Science 2x Weekly","Strength",4,"Intermediate","Strength","Barbell gym"],
  ["stronger-by-science-3x-week","Stronger By Science 3x Weekly","Strength",3,"Intermediate","Strength","Barbell gym"],
  ["stronger-by-science-4x-week","Stronger By Science 4x Weekly","Strength",4,"Intermediate","Strength and muscle","Full gym"],
  ["powerlifting-to-win","Powerlifting To Win Program","Powerlifting",4,"Intermediate","Powerlifting strength","Barbell gym"],
  ["reactive-training-systems-general","Reactive Training Systems General Strength","Powerlifting",4,"Intermediate","Powerlifting strength","Barbell gym"],
  ["tsa-beginner-powerlifting","The Strength Athlete Beginner Powerlifting","Powerlifting",3,"Beginner","Powerlifting technique","Barbell gym"],
  ["calgary-barbell-beginner","Calgary Barbell Beginner Powerlifting","Powerlifting",3,"Beginner","Powerlifting strength","Barbell gym"],
  ["calgary-barbell-intermediate","Calgary Barbell Intermediate Powerlifting","Powerlifting",4,"Intermediate","Competition strength","Barbell gym"],
  ["candito-6-week-advanced","Candito 6 Week Advanced Variation","Powerlifting",5,"Advanced","Powerlifting strength","Barbell gym"],
  ["sheiko-beginner-3-day","Sheiko Beginner 3-Day","Powerlifting",3,"Beginner","Technique and volume","Barbell gym"],
  ["sheiko-intermediate","Sheiko Intermediate","Powerlifting",4,"Intermediate","Technique and volume","Barbell gym"],
  ["westside-conjugate-beginner","Westside Conjugate Beginner","Powerlifting",4,"Intermediate","Strength and power","Barbell gym"],
  ["westside-conjugate-3-day","Westside Conjugate 3-Day","Powerlifting",3,"Intermediate","Powerlifting strength","Barbell gym"],
  ["juggernaut-method-3-day","Juggernaut Method 3-Day","Strength",3,"Intermediate","Strength","Barbell gym"],
  ["juggernaut-method-powerlifting","Juggernaut Powerlifting Template","Powerlifting",4,"Intermediate","Powerlifting strength","Barbell gym"],
  ["starting-strength-2-day","Starting Strength 2-Day","Strength",2,"Beginner","Foundational strength","Barbell gym"],
  ["starting-strength-3-day","Starting Strength 3-Day","Strength",3,"Beginner","Foundational strength","Barbell gym"],
  ["stronglifts-5x5-home","StrongLifts 5x5 Home Variation","Strength",3,"Beginner","Strength","Barbell / home gym"],
  ["madcow-5x5-3-day","Madcow 5x5 3-Day","Strength",3,"Intermediate","Strength","Barbell gym"],
  ["texas-method-3-day","Texas Method 3-Day","Strength",3,"Intermediate","Strength","Barbell gym"],
  ["texas-method-4-day-strength","Texas Method 4-Day Strength","Strength",4,"Advanced","Strength","Barbell gym"],
  ["bill-starr-5x5-intermediate","Bill Starr 5x5 Intermediate","Strength",3,"Intermediate","Strength","Barbell gym"],
  ["greyskull-lp-4-day","Greyskull LP 4-Day","Strength",4,"Beginner","Strength and muscle","Full gym"],
  ["fierce-5-3-day","Fierce 5 3-Day","Strength",3,"Beginner","Strength and muscle","Full gym"],
  ["fierce-5-4-day","Fierce 5 4-Day","Strength",4,"Intermediate","Strength and muscle","Full gym"],
  ["upper-lower-beginner-3-day","Beginner Upper Lower 3-Day","Beginners",3,"Beginner","Strength and muscle","Full gym"],
  ["full-body-beginner-2-day","Beginner Full Body 2-Day","Beginners",2,"Beginner","Strength and fitness","Full gym"],
  ["full-body-beginner-4-day","Beginner Full Body 4-Day","Beginners",4,"Beginner","Strength and muscle","Full gym"],
  ["beginner-machine-full-body","Beginner Machine Full Body","Beginners",3,"Beginner","Strength and fitness","Machines"],
  ["beginner-cable-full-body","Beginner Cable Full Body","Beginners",3,"Beginner","Strength and muscle","Cable gym"],
  ["novice-powerbuilding-3-day","Novice Powerbuilding 3-Day","Powerbuilding",3,"Beginner","Strength and muscle","Full gym"],
  ["novice-powerbuilding-4-day","Novice Powerbuilding 4-Day","Powerbuilding",4,"Beginner","Strength and muscle","Full gym"],
  ["intermediate-powerbuilding-3-day","Intermediate Powerbuilding 3-Day","Powerbuilding",3,"Intermediate","Strength and size","Full gym"],
  ["advanced-powerbuilding-4-day","Advanced Powerbuilding 4-Day","Powerbuilding",4,"Advanced","Strength and size","Full gym"],
  ["powerbuilding-3-day","Powerbuilding 3-Day","Powerbuilding",3,"All Levels","Strength and muscle","Full gym"],
  ["powerbuilding-6-day","Powerbuilding 6-Day","Powerbuilding",6,"Advanced","Strength and size","Full gym"],
  ["hypertrophy-beginner-3-day","Beginner Hypertrophy 3-Day","Hypertrophy",3,"Beginner","Muscle building","Full gym"],
  ["hypertrophy-beginner-4-day","Beginner Hypertrophy 4-Day","Hypertrophy",4,"Beginner","Muscle building","Full gym"],
  ["hypertrophy-intermediate-5-day","Intermediate Hypertrophy 5-Day","Hypertrophy",5,"Intermediate","Muscle building","Full gym"],
  ["hypertrophy-advanced-6-day","Advanced Hypertrophy 6-Day","Hypertrophy",6,"Advanced","Muscle building","Full gym"],
  ["evidence-based-upper-lower","Evidence-Based Upper Lower","Hypertrophy",4,"Intermediate","Muscle building","Full gym"],
  ["evidence-based-ppl","Evidence-Based Push Pull Legs","Hypertrophy",6,"Intermediate","Muscle building","Full gym"],
  ["evidence-based-full-body","Evidence-Based Full Body","Hypertrophy",3,"All Levels","Muscle building","Full gym"],
  ["women-beginner-strength-3-day","Women Beginner Strength 3-Day","Beginners",3,"Beginner","Strength and fitness","Full gym"],
  ["women-strength-3-day","Women Strength 3-Day","Strength",3,"All Levels","Strength and muscle","Full gym"],
  ["women-strength-4-day","Women Strength 4-Day","Strength",4,"Intermediate","Strength and muscle","Full gym"],
  ["women-hypertrophy-4-day","Women Hypertrophy 4-Day","Hypertrophy",4,"Intermediate","Muscle building","Full gym"],
  ["women-glute-hypertrophy-3-day","Women Glute Hypertrophy 3-Day","Hypertrophy",3,"All Levels","Glute and lower-body development","Full gym"],
  ["women-glute-hypertrophy-4-day","Women Glute Hypertrophy 4-Day","Hypertrophy",4,"Intermediate","Glute and lower-body development","Full gym"],
  ["postpartum-return-to-strength","Return to Strength Template","General Fitness",3,"Beginner","Gradual strength rebuilding","Full gym"],
  ["masters-strength-3-day","Masters Strength 3-Day","Strength",3,"All Levels","Strength and consistency","Full gym"],
  ["masters-strength-4-day","Masters Strength 4-Day","Strength",4,"Intermediate","Strength and muscle","Full gym"],
  ["over-40-strength-3-day","Over 40 Strength 3-Day","Strength",3,"All Levels","Strength and fitness","Full gym"],
  ["over-50-strength-3-day","Over 50 Strength 3-Day","Strength",3,"All Levels","Strength and fitness","Full gym"],
  ["over-60-strength-2-day","Over 60 Strength 2-Day","Strength",2,"All Levels","Strength and mobility","Full gym"],
  ["home-dumbbell-2-day","Home Dumbbell 2-Day","Home & Bodyweight",2,"All Levels","Strength and muscle","Dumbbells"],
  ["home-dumbbell-3-day","Home Dumbbell 3-Day","Home & Bodyweight",3,"All Levels","Strength and muscle","Dumbbells"],
  ["home-dumbbell-5-day","Home Dumbbell 5-Day","Home & Bodyweight",5,"Intermediate","Muscle building","Dumbbells"],
  ["adjustable-dumbbell-full-body","Adjustable Dumbbell Full Body","Home & Bodyweight",3,"All Levels","Strength and fitness","Dumbbells"],
  ["resistance-band-full-body","Resistance Band Full Body","Home & Bodyweight",3,"All Levels","Strength and fitness","Resistance bands"],
  ["resistance-band-upper-lower","Resistance Band Upper Lower","Home & Bodyweight",4,"All Levels","Strength and muscle","Resistance bands"],
  ["no-equipment-3-day","No Equipment 3-Day","Home & Bodyweight",3,"Beginner","Strength and fitness","Bodyweight"],
  ["no-equipment-5-day","No Equipment 5-Day","Home & Bodyweight",5,"Intermediate","Fitness and conditioning","Bodyweight"],
  ["travel-workout-2-day","Travel Workout 2-Day","General Fitness",2,"All Levels","Fitness and consistency","Minimal equipment"],
  ["travel-workout-3-day","Travel Workout 3-Day","General Fitness",3,"All Levels","Fitness and consistency","Minimal equipment"],
  ["hotel-dumbbell-3-day","Hotel Dumbbell 3-Day","Home & Bodyweight",3,"All Levels","Strength and fitness","Dumbbells"],
  ["hyrox-12-week","HYROX 12-Week Program","Conditioning",5,"Intermediate","Hybrid endurance and strength","Full gym"],
  ["hyrox-advanced","HYROX Advanced Program","Conditioning",6,"Advanced","Hybrid performance","Full gym"],
  ["hybrid-run-lift-4-day","Hybrid Run + Lift 4-Day","Conditioning",4,"Intermediate","Strength and endurance","Full gym"],
  ["hybrid-run-lift-5-day","Hybrid Run + Lift 5-Day","Conditioning",5,"Advanced","Strength and endurance","Full gym"],
  ["5k-beginner-running","Beginner 5K Running Plan","Conditioning",3,"Beginner","Running fitness","Minimal equipment"],
  ["10k-intermediate-running","Intermediate 10K Running Plan","Conditioning",4,"Intermediate","Running performance","Minimal equipment"],
  ["half-marathon-intermediate","Intermediate Half Marathon Plan","Conditioning",5,"Intermediate","Endurance","Minimal equipment"],
  ["marathon-beginner","Beginner Marathon Plan","Conditioning",4,"Beginner","Endurance","Minimal equipment"],
  ["marathon-intermediate","Intermediate Marathon Plan","Conditioning",5,"Intermediate","Endurance","Minimal equipment"],
  ["triathlon-beginner","Beginner Triathlon Training","Conditioning",5,"Beginner","Multisport endurance","Minimal equipment"],
  ["general-fitness-2-day","General Fitness 2-Day","General Fitness",2,"All Levels","Fitness and consistency","Full gym"],
  ["general-fitness-3-day","General Fitness 3-Day","General Fitness",3,"All Levels","Fitness and consistency","Full gym"],
  ["general-fitness-5-day","General Fitness 5-Day","General Fitness",5,"All Levels","Fitness and conditioning","Full gym"],
  ["strength-mobility-3-day","Strength + Mobility 3-Day","General Fitness",3,"All Levels","Strength and mobility","Full gym"],
  ["functional-strength-3-day","Functional Strength 3-Day","General Fitness",3,"All Levels","Strength and movement quality","Full gym"],
  ["conditioning-3-day","Conditioning 3-Day","Conditioning",3,"All Levels","Work capacity and fitness","Full gym"],
  ["conditioning-4-day","Conditioning 4-Day","Conditioning",4,"Intermediate","Work capacity and fitness","Full gym"],
];

const desc = (r: Row) => `${r[1]} is a ${r[3]}-day ${r[2].toLowerCase()} training approach focused on ${r[5].toLowerCase()}. Use this page to understand the training style and organize the routine in Gym Log.`;
const structure = (r: Row) => r[2] === "Strength" || r[2] === "Powerlifting" ? ["Primary strength movements", "Supplemental work", "Accessory exercises", "Progressive loading"] : r[2] === "Hypertrophy" || r[2] === "Bodybuilding" || r[2] === "Powerbuilding" ? ["Main movement patterns", "Hypertrophy-focused work", "Accessory exercises", "Manage weekly volume"] : r[2] === "Home & Bodyweight" || r[2] === "Beginners" ? ["Primary movement patterns", "Strength or fitness work", "Progress gradually", "Adjust around recovery"] : ["Strength or conditioning work", "Supporting exercises", "Progress gradually", "Adjust around recovery"];

export const EXTRA_PROGRAMS_4: Program[] = rows.map(r => ({
  slug: r[0], name: r[1], category: r[2], days: r[3], level: r[4], goal: r[5], equipment: r[6],
  description: desc(r),
  bestFor: `People seeking a structured ${r[2].toLowerCase()} routine with a clear weekly schedule.`,
  structure: structure(r),
  notes: "This page is an informational overview. For named programs, use the current author or official source for exact prescriptions. Gym Log helps you organize and track the routine you choose."
}));
