import type { Program } from "./programs";

type Row=[string,string,string,number,Program["level"],string,string];
const rows:Row[]=[
["starting-strength-advanced","Starting Strength Advanced","Strength",3,"Advanced","Strength","Barbell gym"],
["stronglifts-5x5-3-day","StrongLifts 5×5 3-Day","Strength",3,"Beginner","Strength","Barbell gym"],
["stronglifts-5x5-4-day","StrongLifts 5×5 4-Day","Strength",4,"Intermediate","Strength","Barbell gym"],
["madcow-5x5-advanced","Madcow 5×5 Advanced","Strength",3,"Advanced","Strength","Barbell gym"],
["texas-method-4-day","Texas Method 4-Day","Strength",4,"Advanced","Strength","Barbell gym"],
["531-triumvirate","5/3/1 Triumvirate","Strength",4,"Intermediate","Strength","Barbell gym"],
["531-pervertor","5/3/1 Pervertor","Strength",4,"Intermediate","Strength and size","Barbell gym"],
["531-simplest-strength","5/3/1 Simplest Strength","Strength",3,"Intermediate","Strength","Barbell gym"],
["531-jokers-wild","5/3/1 Joker Sets","Strength",4,"Intermediate","Strength","Barbell gym"],
["gzclp-3-day","GZCLP 3-Day","Strength",3,"Beginner","Strength","Barbell gym"],
["gzclp-4-day","GZCLP 4-Day","Strength",4,"Beginner","Strength","Barbell gym"],
["gzcl-u4","GZCL U4","Strength",4,"Intermediate","Strength and hypertrophy","Barbell gym"],
["greyskull-lp-3-day","Greyskull LP 3-Day","Strength",3,"Beginner","Strength","Barbell gym"],
["fierce-5-upper-lower","Fierce 5 Upper Lower","Strength",4,"Intermediate","Strength and muscle","Full gym"],
["fierce-5-full-body","Fierce 5 Full Body","Strength",3,"Beginner","Strength and muscle","Full gym"],
["stronger-by-science-rts","Stronger By Science Strength Template","Strength",4,"Intermediate","Strength","Barbell gym"],
["stronger-by-science-rtf","Reactive Training Systems Strength Template","Powerlifting",4,"Intermediate","Powerlifting strength","Barbell gym"],
["juggernaut-method-2","Juggernaut Method 2.0","Strength",4,"Intermediate","Strength","Barbell gym"],
["juggernaut-ai","JuggernautAI Powerlifting","Powerlifting",4,"Intermediate","Powerlifting strength","Barbell gym"],
["sheiko-advanced","Sheiko Advanced","Powerlifting",4,"Advanced","Powerlifting strength","Barbell gym"],
["sheiko-29-extended","Sheiko #29 Extended","Powerlifting",4,"Intermediate","Powerlifting volume","Barbell gym"],
["smolov-jr-bench","Smolov Jr Bench","Powerlifting",4,"Intermediate","Bench strength","Barbell gym"],
["smolov-jr-squat","Smolov Jr Squat","Powerlifting",4,"Intermediate","Squat strength","Barbell gym"],
["coan-phillipi-deadlift-advanced","Coan/Phillipi Deadlift Advanced","Powerlifting",1,"Advanced","Deadlift strength","Barbell gym"],
["bench-press-3-day","Bench Press 3-Day","Powerlifting",3,"Intermediate","Bench strength","Barbell gym"],
["bench-press-4-day","Bench Press 4-Day","Powerlifting",4,"Advanced","Bench strength","Barbell gym"],
["squat-3-day","Squat 3-Day","Powerlifting",3,"Intermediate","Squat strength","Barbell gym"],
["deadlift-2-day","Deadlift 2-Day","Powerlifting",2,"Intermediate","Deadlift strength","Barbell gym"],
["powerlifting-beginner-3-day","Beginner Powerlifting 3-Day","Powerlifting",3,"Beginner","Powerlifting technique","Barbell gym"],
["powerlifting-intermediate-4-day","Intermediate Powerlifting 4-Day","Powerlifting",4,"Intermediate","Competition strength","Barbell gym"],
["powerlifting-advanced-5-day","Advanced Powerlifting 5-Day","Powerlifting",5,"Advanced","Competition strength","Barbell gym"],
["bodybuilding-beginner-3-day","Beginner Bodybuilding 3-Day","Bodybuilding",3,"Beginner","Muscle building","Full gym"],
["bodybuilding-intermediate-4-day","Intermediate Bodybuilding 4-Day","Bodybuilding",4,"Intermediate","Muscle building","Full gym"],
["bodybuilding-advanced-5-day","Advanced Bodybuilding 5-Day","Bodybuilding",5,"Advanced","Muscle building","Full gym"],
["bodybuilding-6-day-ppl","Bodybuilding 6-Day PPL","Bodybuilding",6,"Advanced","Muscle building","Full gym"],
["upper-lower-strength-hypertrophy","Upper Lower Strength & Hypertrophy","Powerbuilding",4,"Intermediate","Strength and muscle","Full gym"],
["full-body-strength-hypertrophy-3","Full Body Strength & Hypertrophy 3-Day","Powerbuilding",3,"Intermediate","Strength and muscle","Full gym"],
["full-body-strength-hypertrophy-4","Full Body Strength & Hypertrophy 4-Day","Powerbuilding",4,"Intermediate","Strength and muscle","Full gym"],
["push-pull-legs-3-day","Push Pull Legs 3-Day","Hypertrophy",3,"All Levels","Muscle and strength","Full gym"],
["push-pull-legs-4-day","Push Pull Legs 4-Day","Hypertrophy",4,"Intermediate","Muscle building","Full gym"],
["push-pull-legs-5-day","Push Pull Legs 5-Day","Hypertrophy",5,"Intermediate","Muscle building","Full gym"],
["upper-lower-3-day","Upper Lower 3-Day","Hypertrophy",3,"All Levels","Muscle and strength","Full gym"],
["upper-lower-6-day","Upper Lower 6-Day","Hypertrophy",6,"Advanced","Muscle building","Full gym"],
["full-body-2-day-hypertrophy","Full Body 2-Day Hypertrophy","Hypertrophy",2,"All Levels","Muscle building","Full gym"],
["full-body-5-day-hypertrophy","Full Body 5-Day Hypertrophy","Hypertrophy",5,"Advanced","Muscle building","Full gym"],
["dumbbell-3-day-muscle","Dumbbell 3-Day Muscle Building","Hypertrophy",3,"All Levels","Muscle building","Dumbbells"],
["dumbbell-5-day-muscle","Dumbbell 5-Day Muscle Building","Hypertrophy",5,"Intermediate","Muscle building","Dumbbells"],
["home-full-body-2-day","Home Full Body 2-Day","Home & Bodyweight",2,"All Levels","Strength and fitness","Home gym"],
["home-full-body-4-day","Home Full Body 4-Day","Home & Bodyweight",4,"All Levels","Strength and fitness","Home gym"],
["bodyweight-upper-lower","Bodyweight Upper Lower","Calisthenics",4,"Intermediate","Relative strength","Bodyweight / bars"],
["calisthenics-intermediate","Calisthenics Intermediate","Calisthenics",4,"Intermediate","Relative strength","Bodyweight / bars"],
["kettlebell-2-day","Kettlebell 2-Day","Kettlebell",2,"Beginner","Strength and conditioning","Kettlebell"],
["kettlebell-4-day","Kettlebell 4-Day","Kettlebell",4,"Intermediate","Strength and conditioning","Kettlebell"],
["hyrox-beginner","HYROX Beginner Program","Conditioning",4,"Beginner","Hybrid fitness","Full gym"],
["hyrox-intermediate","HYROX Intermediate Program","Conditioning",5,"Intermediate","Hybrid fitness","Full gym"],
["10k-running-plan","10K Running Plan","Conditioning",4,"Beginner","Running fitness","Minimal equipment"],
["half-marathon-beginner","Half Marathon Beginner Plan","Conditioning",4,"Beginner","Endurance","Minimal equipment"],
["hybrid-run-lift-3-day","Hybrid Run + Lift 3-Day","Conditioning",3,"Intermediate","Strength and endurance","Full gym"],
["athlete-strength-2-day","Athlete Strength 2-Day","Conditioning",2,"All Levels","Strength maintenance","Full gym"],
["athlete-strength-3-day","Athlete Strength 3-Day","Conditioning",3,"Intermediate","Athletic performance","Full gym"],
];
const desc=(r:Row)=>`${r[1]} is a ${r[3]}-day ${r[2].toLowerCase()} training approach focused on ${r[5].toLowerCase()}. Use this page to understand the structure and organize the routine in Gym Log.`;
const structure=(r:Row)=>r[2]==="Strength"||r[2]==="Powerlifting"?["Primary strength movements","Supplemental work","Accessory exercises","Progressive loading"]:r[2]==="Hypertrophy"||r[2]==="Bodybuilding"||r[2]==="Powerbuilding"?["Main movement patterns","Hypertrophy-focused work","Accessory exercises","Manage weekly volume"]:r[2]==="Calisthenics"||r[2]==="Kettlebell"?["Primary movement or skill","Strength work","Progression work","Manage recovery"]:["Strength or conditioning work","Supporting exercises","Progress gradually","Adjust around recovery"];
export const EXTRA_PROGRAMS_3:Program[]=rows.map(r=>({slug:r[0],name:r[1],category:r[2],days:r[3],level:r[4],goal:r[5],equipment:r[6],description:desc(r),bestFor:`People seeking a structured ${r[2].toLowerCase()} routine with a clear weekly schedule.`,structure:structure(r),notes:"This page is an informational overview. For named programs, use the current author or official source for exact prescriptions. Gym Log helps you organize and track the routine you choose."}));
