export type ExerciseCategory = "Chest" | "Back" | "Shoulders" | "Arms" | "Legs" | "Glutes" | "Core" | "Full Body" | "Cardio" | "Bodyweight";
export type ExerciseDifficulty = "Beginner" | "Intermediate" | "Advanced";

export type Exercise = {
  slug: string;
  name: string;
  category: ExerciseCategory;
  movementPattern: string;
  equipment: string[];
  primaryMuscles: string[];
  secondaryMuscles: string[];
  difficulty: ExerciseDifficulty;
  exerciseType: "Compound" | "Isolation" | "Cardio";
  description: string;
  instructions: string[];
  tips: string[];
  commonMistakes: string[];
  alternatives: string[];
};

const make = (data: Exercise): Exercise => data;

export const EXERCISE_DATABASE: Exercise[] = [
make({slug:"barbell-bench-press",name:"Barbell Bench Press",category:"Chest",movementPattern:"Horizontal Push",equipment:["Barbell","Bench"],primaryMuscles:["Chest"],secondaryMuscles:["Triceps","Front delts"],difficulty:"Intermediate",exerciseType:"Compound",description:"A foundational horizontal press for building chest, triceps and shoulder strength.",instructions:["Lie on the bench with your eyes under the bar, feet planted and upper back supported.","Brace your trunk and lower the bar under control toward the lower-to-mid chest.","Press the bar back up while keeping your shoulders stable and wrists stacked."],tips:["Use a grip that feels strong and comfortable rather than forcing a specific width.","Keep the bar path controlled and consistent."],commonMistakes:["Bouncing the bar","Excessive elbow flare","Losing upper-back tension"],alternatives:["dumbbell-bench-press","incline-barbell-bench-press","push-up"]}),
make({slug:"incline-barbell-bench-press",name:"Incline Barbell Bench Press",category:"Chest",movementPattern:"Horizontal Push",equipment:["Barbell","Incline bench"],primaryMuscles:["Upper chest"],secondaryMuscles:["Triceps","Front delts"],difficulty:"Intermediate",exerciseType:"Compound",description:"An incline pressing variation that places more emphasis on the upper chest.",instructions:["Set a moderate bench incline and position your upper back securely.","Lower the bar toward the upper chest with a controlled descent.","Press upward without allowing the shoulders to roll forward."],tips:["A moderate incline is usually easier to control than a very steep angle.","Keep your feet planted throughout the set."],commonMistakes:["Using an excessively steep incline","Letting shoulders dominate","Losing wrist alignment"],alternatives:["barbell-bench-press","incline-dumbbell-bench-press","machine-chest-press"]}),
make({slug:"dumbbell-bench-press",name:"Dumbbell Bench Press",category:"Chest",movementPattern:"Horizontal Push",equipment:["Dumbbells","Bench"],primaryMuscles:["Chest"],secondaryMuscles:["Triceps","Front delts"],difficulty:"Beginner",exerciseType:"Compound",description:"A dumbbell press that trains the chest while allowing each arm to work independently.",instructions:["Set the dumbbells over your chest with your feet planted and upper back supported.","Lower both weights under control until you reach a comfortable stretch.","Press them upward smoothly while keeping both sides balanced."],tips:["Choose a range of motion you can control without shoulder discomfort.","Avoid crashing the dumbbells together at the top."],commonMistakes:["Using momentum","Uneven pressing","Dropping the elbows excessively low"],alternatives:["barbell-bench-press","incline-dumbbell-bench-press","push-up"]}),
make({slug:"push-up",name:"Push-Up",category:"Chest",movementPattern:"Horizontal Push",equipment:["Bodyweight"],primaryMuscles:["Chest"],secondaryMuscles:["Triceps","Front delts","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A bodyweight horizontal press that also challenges trunk stability.",instructions:["Start in a strong plank with hands slightly wider than shoulder width.","Lower your body as one unit while keeping your elbows in a comfortable path.","Press the floor away to return to the plank position."],tips:["Brace your abs and squeeze your glutes.","Use an elevated surface to scale the movement."],commonMistakes:["Sagging hips","Leading with the head","Flaring the elbows"],alternatives:["incline-push-up","dumbbell-bench-press","chest-dip"]}),
make({slug:"cable-chest-fly",name:"Cable Chest Fly",category:"Chest",movementPattern:"Horizontal Adduction",equipment:["Cable machine"],primaryMuscles:["Chest"],secondaryMuscles:["Front delts"],difficulty:"Beginner",exerciseType:"Isolation",description:"A cable fly that keeps resistance on the chest through much of the movement.",instructions:["Set the handles around chest height and take a stable stance.","Bring the handles together in front of your chest with a soft elbow bend.","Return slowly until you feel a controlled stretch."],tips:["Think about bringing the upper arms together rather than just the hands.","Use a load that keeps the movement smooth."],commonMistakes:["Turning the movement into a press","Using too much weight","Excessive elbow movement"],alternatives:["pec-deck-fly","dumbbell-fly","push-up"]}),
make({slug:"deadlift",name:"Deadlift",category:"Back",movementPattern:"Hinge",equipment:["Barbell"],primaryMuscles:["Glutes","Hamstrings","Back"],secondaryMuscles:["Core","Forearms","Quads"],difficulty:"Intermediate",exerciseType:"Compound",description:"A full-body hinge that develops posterior-chain strength from the floor.",instructions:["Stand with the bar over your mid-foot and take a balanced stance.","Hinge down, grip the bar, brace and create tension before lifting.","Push through the floor and extend the hips and knees together, then lower with control."],tips:["Keep the bar close to your legs.","Build tension before the bar leaves the floor."],commonMistakes:["Starting with the bar too far away","Jerking the bar from the floor","Losing a stable trunk position"],alternatives:["romanian-deadlift","trap-bar-deadlift","rack-pull"]}),
make({slug:"romanian-deadlift",name:"Romanian Deadlift",category:"Back",movementPattern:"Hinge",equipment:["Barbell"],primaryMuscles:["Hamstrings","Glutes"],secondaryMuscles:["Back","Forearms"],difficulty:"Intermediate",exerciseType:"Compound",description:"A controlled hip hinge that emphasizes the hamstrings and glutes.",instructions:["Stand tall with the bar against your thighs and knees slightly unlocked.","Push your hips back while keeping the bar close until the hamstrings are loaded.","Drive the hips forward to stand tall without leaning backward."],tips:["Think hips back rather than bar down.","Stop the descent when your position starts to deteriorate."],commonMistakes:["Squatting the weight down","Letting the bar drift away","Overextending at the top"],alternatives:["deadlift","dumbbell-romanian-deadlift","good-morning"]}),
make({slug:"barbell-row",name:"Barbell Row",category:"Back",movementPattern:"Horizontal Pull",equipment:["Barbell"],primaryMuscles:["Upper back","Lats"],secondaryMuscles:["Biceps","Rear delts","Core"],difficulty:"Intermediate",exerciseType:"Compound",description:"A bent-over pulling exercise for the lats and upper back.",instructions:["Hinge into a stable torso position with the bar hanging below you.","Pull the bar toward your lower ribs while keeping the torso position controlled.","Lower the bar under control without turning the movement into a shrug."],tips:["Keep the load close to your body.","Use a torso angle you can maintain consistently."],commonMistakes:["Standing too upright","Excessive body swing","Shrugging instead of rowing"],alternatives:["dumbbell-row","chest-supported-row","seated-cable-row"]}),
make({slug:"dumbbell-row",name:"One-Arm Dumbbell Row",category:"Back",movementPattern:"Horizontal Pull",equipment:["Dumbbell","Bench"],primaryMuscles:["Lats","Upper back"],secondaryMuscles:["Biceps","Rear delts"],difficulty:"Beginner",exerciseType:"Compound",description:"A unilateral row that lets each side work independently while the torso is supported.",instructions:["Support one hand and knee on a bench and let the dumbbell hang under the shoulder.","Pull the dumbbell toward your hip while keeping the torso stable.","Lower it slowly to the starting position."],tips:["Drive the elbow back rather than curling the weight.","Avoid rotating the torso to finish a rep."],commonMistakes:["Twisting the torso","Shrugging","Using momentum"],alternatives:["barbell-row","chest-supported-row","seated-cable-row"]}),
make({slug:"chest-supported-row",name:"Chest-Supported Row",category:"Back",movementPattern:"Horizontal Pull",equipment:["Dumbbells","Incline bench"],primaryMuscles:["Upper back","Lats"],secondaryMuscles:["Biceps","Rear delts"],difficulty:"Beginner",exerciseType:"Compound",description:"A supported row that reduces the need to stabilize the torso.",instructions:["Set an incline bench and lie face down with the weights hanging below you.","Pull the weights toward your lower ribs while keeping your chest supported.","Lower slowly until your arms are extended without losing shoulder control."],tips:["Keep the chest planted throughout.","Pause at the top if you can maintain position."],commonMistakes:["Lifting the chest off the bench","Shrugging","Using a shortened range"],alternatives:["dumbbell-row","barbell-row","seated-cable-row"]}),
make({slug:"seated-cable-row",name:"Seated Cable Row",category:"Back",movementPattern:"Horizontal Pull",equipment:["Cable machine"],primaryMuscles:["Upper back","Lats"],secondaryMuscles:["Biceps","Rear delts"],difficulty:"Beginner",exerciseType:"Compound",description:"A stable horizontal pull for the mid-back and lats.",instructions:["Sit tall with your feet supported and hold the handle comfortably.","Pull the handle toward your torso while keeping your chest controlled.","Extend your arms slowly without collapsing your torso."],tips:["Lead with the elbows and keep the shoulders down.","Use a range of motion you can control."],commonMistakes:["Rocking backward","Shrugging","Rounding the lower back"],alternatives:["barbell-row","dumbbell-row","chest-supported-row"]}),
make({slug:"lat-pulldown",name:"Lat Pulldown",category:"Back",movementPattern:"Vertical Pull",equipment:["Cable machine"],primaryMuscles:["Lats"],secondaryMuscles:["Biceps","Upper back"],difficulty:"Beginner",exerciseType:"Compound",description:"A scalable vertical pull for developing the lats and upper back.",instructions:["Sit securely and grip the bar slightly wider than shoulder width.","Pull the bar toward the upper chest while keeping your torso stable.","Return the bar upward under control without losing shoulder position."],tips:["Think elbows down toward your sides.","Avoid leaning far backward to turn it into a row."],commonMistakes:["Pulling behind the neck","Excessive swinging","Using momentum to start the rep"],alternatives:["pull-up","assisted-pull-up","straight-arm-pulldown"]}),
make({slug:"pull-up",name:"Pull-Up",category:"Back",movementPattern:"Vertical Pull",equipment:["Pull-up bar"],primaryMuscles:["Lats"],secondaryMuscles:["Biceps","Core","Upper back"],difficulty:"Intermediate",exerciseType:"Compound",description:"A bodyweight vertical pull that develops back and arm strength.",instructions:["Hang from the bar with a controlled grip and your body braced.","Pull your elbows down and back to raise your chest toward the bar.","Lower yourself under control until your arms are extended."],tips:["Keep the legs controlled instead of kicking.","Use assistance to build clean repetitions if needed."],commonMistakes:["Unintentional kipping","Shrugging throughout","Cutting the range short"],alternatives:["lat-pulldown","assisted-pull-up","chin-up"]}),
make({slug:"chin-up",name:"Chin-Up",category:"Back",movementPattern:"Vertical Pull",equipment:["Pull-up bar"],primaryMuscles:["Lats","Biceps"],secondaryMuscles:["Upper back","Core"],difficulty:"Intermediate",exerciseType:"Compound",description:"A supinated-grip pull-up variation with strong biceps contribution.",instructions:["Hang from the bar with palms facing toward you and brace your trunk.","Pull your elbows toward your sides until you reach the top position.","Lower under control to the starting hang."],tips:["Keep the ribs and pelvis controlled.","Use assistance when necessary to keep reps smooth."],commonMistakes:["Swinging","Shrugging excessively","Partial repetitions"],alternatives:["pull-up","lat-pulldown","assisted-pull-up"]}),
make({slug:"back-squat",name:"Barbell Back Squat",category:"Legs",movementPattern:"Squat",equipment:["Barbell","Rack"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Adductors","Core","Hamstrings"],difficulty:"Intermediate",exerciseType:"Compound",description:"A foundational squat for lower-body and trunk strength.",instructions:["Unrack the bar securely and set a stance that lets you balance comfortably.","Brace, bend the knees and hips, and descend while keeping the bar balanced over the mid-foot.","Drive through the floor and stand tall while maintaining your trunk position."],tips:["Use a depth you can control with stable foot pressure.","Keep the bar path consistent from rep to rep."],commonMistakes:["Knees collapsing inward","Losing balance onto the toes","Descending without bracing"],alternatives:["front-squat","goblet-squat","leg-press"]}),
make({slug:"front-squat",name:"Front Squat",category:"Legs",movementPattern:"Squat",equipment:["Barbell","Rack"],primaryMuscles:["Quads"],secondaryMuscles:["Glutes","Core","Upper back"],difficulty:"Intermediate",exerciseType:"Compound",description:"A front-loaded squat that increases the demand on the quads and trunk.",instructions:["Position the bar securely across the front shoulders with elbows lifted.","Brace and squat while keeping the torso relatively upright.","Drive through the floor without letting the elbows drop."],tips:["Use a grip that lets you keep the bar secure.","Start light while learning the front-rack position."],commonMistakes:["Elbows dropping","Bar rolling forward","Losing the brace"],alternatives:["back-squat","goblet-squat","leg-press"]}),
make({slug:"goblet-squat",name:"Goblet Squat",category:"Legs",movementPattern:"Squat",equipment:["Dumbbell or kettlebell"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Core","Adductors"],difficulty:"Beginner",exerciseType:"Compound",description:"A front-loaded squat that is useful for learning the squat pattern.",instructions:["Hold the weight close to your chest and stand with a comfortable stance.","Sit down between your hips while keeping the weight close and feet planted.","Drive through the floor to stand tall."],tips:["Use the front-loaded weight to practice an upright torso.","Move through a depth you can control."],commonMistakes:["Weight drifting away","Heels lifting","Collapsing the torso"],alternatives:["back-squat","front-squat","leg-press"]}),
make({slug:"leg-press",name:"Leg Press",category:"Legs",movementPattern:"Knee Extension",equipment:["Leg press machine"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Hamstrings"],difficulty:"Beginner",exerciseType:"Compound",description:"A machine-based lower-body press with external support.",instructions:["Set the seat and foot position so your knees and hips move comfortably.","Lower the platform under control while keeping your feet stable.","Press the platform away without forcefully locking the knees."],tips:["Use a range that keeps your lower back supported.","Control the platform in both directions."],commonMistakes:["Lowering beyond a controllable range","Knees caving inward","Aggressive knee lockout"],alternatives:["back-squat","hack-squat","split-squat"]}),
make({slug:"bulgarian-split-squat",name:"Bulgarian Split Squat",category:"Legs",movementPattern:"Single-Leg Squat",equipment:["Dumbbells","Bench"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Adductors","Core"],difficulty:"Intermediate",exerciseType:"Compound",description:"A rear-foot-elevated single-leg squat that challenges strength and balance.",instructions:["Place the rear foot on a bench and establish a stable front-foot position.","Lower the hips while keeping the front foot planted and torso controlled.","Drive through the front foot to return to the starting position."],tips:["Find your stance before adding heavy loads.","Use support for balance while learning the movement."],commonMistakes:["Front foot too close","Pushing mostly from the rear leg","Losing balance through the torso"],alternatives:["split-squat","walking-lunge","reverse-lunge"]}),
make({slug:"walking-lunge",name:"Walking Lunge",category:"Legs",movementPattern:"Lunge",equipment:["Bodyweight or dumbbells"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Hamstrings","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A stepping lunge that trains each leg independently while challenging coordination.",instructions:["Stand tall and take a controlled step forward.","Lower the rear knee toward the floor while keeping the front foot stable.","Push through the front foot and step forward into the next repetition."],tips:["Keep steps long enough to stay balanced.","Use bodyweight first if balance is limiting."],commonMistakes:["Knee collapsing inward","Unstable steps","Rushing between reps"],alternatives:["reverse-lunge","bulgarian-split-squat","split-squat"]}),
make({slug:"leg-extension",name:"Leg Extension",category:"Legs",movementPattern:"Knee Extension",equipment:["Leg extension machine"],primaryMuscles:["Quads"],secondaryMuscles:[],difficulty:"Beginner",exerciseType:"Isolation",description:"A machine isolation exercise focused on the quadriceps.",instructions:["Adjust the seat and pad so the knee joint lines up with the machine pivot.","Extend the knees smoothly until the legs are nearly straight.","Lower the pad slowly to the starting position."],tips:["Use a controlled tempo and comfortable range.","Keep your hips against the seat."],commonMistakes:["Using momentum","Poor machine setup","Slamming the weight down"],alternatives:["leg-press","goblet-squat","split-squat"]}),
make({slug:"lying-leg-curl",name:"Lying Leg Curl",category:"Legs",movementPattern:"Knee Flexion",equipment:["Leg curl machine"],primaryMuscles:["Hamstrings"],secondaryMuscles:["Calves"],difficulty:"Beginner",exerciseType:"Isolation",description:"A machine curl that trains the hamstrings through knee flexion.",instructions:["Set the machine so the knee aligns with the pivot and the pad rests comfortably above the ankles.","Curl the lower legs toward the body without lifting the hips.","Lower the weight slowly to controlled extension."],tips:["Keep the pelvis stable against the pad.","Use a load that allows a smooth lowering phase."],commonMistakes:["Raising the hips","Using momentum","Shortening the range"],alternatives:["seated-leg-curl","romanian-deadlift","nordic-hamstring-curl"]}),
make({slug:"barbell-overhead-press",name:"Barbell Overhead Press",category:"Shoulders",movementPattern:"Vertical Push",equipment:["Barbell","Rack"],primaryMuscles:["Shoulders"],secondaryMuscles:["Triceps","Upper chest","Core"],difficulty:"Intermediate",exerciseType:"Compound",description:"A standing barbell press that develops shoulder and upper-body pressing strength.",instructions:["Start with the bar at upper-chest height and brace your trunk.","Press the bar upward while moving your head out of the bar's path.","Finish in a stable overhead position and lower under control."],tips:["Squeeze the glutes and brace before each rep.","Keep the bar close to your body."],commonMistakes:["Leaning backward","Pressing around the face","Losing trunk tension"],alternatives:["dumbbell-shoulder-press","machine-shoulder-press","push-press"]}),
make({slug:"dumbbell-shoulder-press",name:"Dumbbell Shoulder Press",category:"Shoulders",movementPattern:"Vertical Push",equipment:["Dumbbells","Bench"],primaryMuscles:["Shoulders"],secondaryMuscles:["Triceps","Upper chest"],difficulty:"Beginner",exerciseType:"Compound",description:"A seated or standing dumbbell press for the shoulders and triceps.",instructions:["Set the dumbbells at shoulder level with a stable position.","Press the weights upward while keeping the ribs and trunk controlled.","Lower them slowly to shoulder level."],tips:["Choose a comfortable elbow position.","Use back support if it helps you maintain control."],commonMistakes:["Excessive back arch","Using leg momentum","Uneven pressing"],alternatives:["barbell-overhead-press","machine-shoulder-press","lateral-raise"]}),
make({slug:"lateral-raise",name:"Dumbbell Lateral Raise",category:"Shoulders",movementPattern:"Shoulder Abduction",equipment:["Dumbbells"],primaryMuscles:["Lateral delts"],secondaryMuscles:["Traps"],difficulty:"Beginner",exerciseType:"Isolation",description:"A shoulder isolation exercise emphasizing the lateral deltoids.",instructions:["Stand tall with light dumbbells and a soft elbow bend.","Raise the arms out to the sides in a controlled arc.","Lower slowly without swinging the weights."],tips:["Use lighter weights than you expect.","Lead the movement with the elbows and stop at a comfortable height."],commonMistakes:["Swinging","Shrugging excessively","Using too much weight"],alternatives:["cable-lateral-raise","machine-lateral-raise","dumbbell-shoulder-press"]}),
make({slug:"face-pull",name:"Face Pull",category:"Shoulders",movementPattern:"Horizontal Pull",equipment:["Cable machine","Rope"],primaryMuscles:["Rear delts","Upper back"],secondaryMuscles:["Rotator cuff","Traps"],difficulty:"Beginner",exerciseType:"Isolation",description:"A cable pull toward the face that trains the rear shoulders and upper back.",instructions:["Set a rope around upper-chest to face height and take a stable stance.","Pull the rope toward your face while allowing the hands to separate.","Return under control while keeping the shoulders comfortable."],tips:["Keep the load moderate and focus on control.","Avoid turning the movement into a heavy row."],commonMistakes:["Using excessive weight","Shrugging","Pulling too low"],alternatives:["rear-delt-fly","cable-row","reverse-pec-deck"]}),
make({slug:"barbell-curl",name:"Barbell Curl",category:"Arms",movementPattern:"Elbow Flexion",equipment:["Barbell"],primaryMuscles:["Biceps"],secondaryMuscles:["Forearms"],difficulty:"Beginner",exerciseType:"Isolation",description:"A simple curl for building elbow-flexor strength and biceps size.",instructions:["Stand tall with the bar at your thighs and elbows near your sides.","Curl the bar upward without moving the elbows forward excessively.","Lower the bar slowly until the elbows are comfortably extended."],tips:["Keep the torso still.","Use a controlled lowering phase."],commonMistakes:["Swinging the torso","Throwing the shoulders forward","Using excessive load"],alternatives:["dumbbell-curl","hammer-curl","preacher-curl"]}),
make({slug:"hammer-curl",name:"Hammer Curl",category:"Arms",movementPattern:"Elbow Flexion",equipment:["Dumbbells"],primaryMuscles:["Brachialis","Biceps"],secondaryMuscles:["Forearms"],difficulty:"Beginner",exerciseType:"Isolation",description:"A neutral-grip curl that emphasizes the brachialis, biceps and forearms.",instructions:["Hold the dumbbells with palms facing each other.","Curl the weights while keeping the elbows near your sides.","Lower under control to the starting position."],tips:["Keep the neutral grip consistent.","Avoid turning the exercise into a swing."],commonMistakes:["Using body momentum","Elbows drifting forward","Shrugging"],alternatives:["dumbbell-curl","barbell-curl","preacher-curl"]}),
make({slug:"triceps-pushdown",name:"Cable Triceps Pushdown",category:"Arms",movementPattern:"Elbow Extension",equipment:["Cable machine"],primaryMuscles:["Triceps"],secondaryMuscles:[],difficulty:"Beginner",exerciseType:"Isolation",description:"A cable isolation exercise for the triceps using a stable standing position.",instructions:["Stand facing the cable with elbows close to your sides.","Extend the elbows to drive the handle down without swinging the shoulders.","Return the handle slowly until the triceps are lengthened."],tips:["Keep the upper arms mostly stationary.","Choose a load that does not pull your shoulders forward."],commonMistakes:["Turning it into a press","Elbows flaring widely","Using torso momentum"],alternatives:["overhead-triceps-extension","skull-crusher","close-grip-bench-press"]}),
make({slug:"overhead-triceps-extension",name:"Overhead Triceps Extension",category:"Arms",movementPattern:"Elbow Extension",equipment:["Dumbbell or cable"],primaryMuscles:["Triceps"],secondaryMuscles:["Shoulders"],difficulty:"Beginner",exerciseType:"Isolation",description:"An overhead triceps movement that trains elbow extension through a longer muscle length.",instructions:["Hold the weight overhead with the elbows pointing generally forward.","Bend the elbows to lower the weight behind your head while keeping the upper arms controlled.","Extend the elbows to return overhead."],tips:["Use a comfortable range and moderate load.","Keep the ribs controlled instead of overextending the lower back."],commonMistakes:["Excessive elbow flare","Arching the back","Using too much weight"],alternatives:["triceps-pushdown","skull-crusher","close-grip-bench-press"]}),
make({slug:"hip-thrust",name:"Barbell Hip Thrust",category:"Glutes",movementPattern:"Hip Extension",equipment:["Barbell","Bench"],primaryMuscles:["Glutes"],secondaryMuscles:["Hamstrings"],difficulty:"Intermediate",exerciseType:"Compound",description:"A supported hip-extension exercise that strongly trains the glutes.",instructions:["Set your upper back against a stable bench with the bar positioned over the hips.","Drive through the feet to extend the hips while keeping the ribs controlled.","Pause briefly at the top if comfortable, then lower under control."],tips:["Use a pad for the bar when needed.","Finish by extending the hips rather than arching the lower back."],commonMistakes:["Overarching at the top","Poor foot position","Rushing the lowering phase"],alternatives:["glute-bridge","romanian-deadlift","cable-pull-through"]}),
make({slug:"glute-bridge",name:"Glute Bridge",category:"Glutes",movementPattern:"Hip Extension",equipment:["Bodyweight"],primaryMuscles:["Glutes"],secondaryMuscles:["Hamstrings","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A simple floor-based hip extension exercise for learning glute engagement.",instructions:["Lie on your back with knees bent and feet planted.","Drive through the feet to raise the hips while keeping the ribs controlled.","Lower the hips slowly and repeat."],tips:["Squeeze the glutes at the top without forcing the lower back into extension.","Add load when bodyweight becomes easy."],commonMistakes:["Arching the lower back","Pushing mostly through the toes","Moving too quickly"],alternatives:["hip-thrust","cable-pull-through","romanian-deadlift"]}),
make({slug:"cable-pull-through",name:"Cable Pull-Through",category:"Glutes",movementPattern:"Hinge",equipment:["Cable machine","Rope"],primaryMuscles:["Glutes"],secondaryMuscles:["Hamstrings","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A cable hinge that teaches hip extension with continuous resistance.",instructions:["Stand facing away from a low cable with the rope between your legs.","Hinge the hips back while keeping the cable close to your body.","Drive the hips forward to stand tall without leaning backward."],tips:["Think hips back, then squeeze the glutes forward.","Keep the spine stable throughout."],commonMistakes:["Squatting instead of hinging","Rounding the back","Overextending at the top"],alternatives:["romanian-deadlift","hip-thrust","kettlebell-swing"]}),
make({slug:"plank",name:"Front Plank",category:"Core",movementPattern:"Anti-Extension",equipment:["Bodyweight"],primaryMuscles:["Abdominals"],secondaryMuscles:["Glutes","Shoulders"],difficulty:"Beginner",exerciseType:"Isolation",description:"An isometric trunk exercise that trains bracing and resistance to spinal extension.",instructions:["Set up on your forearms or hands with your body in a straight line.","Brace your abs and glutes while keeping the pelvis neutral.","Hold the position without letting the hips sag or rise excessively."],tips:["Think about pulling the ribs toward the pelvis.","End the set when you can no longer maintain position."],commonMistakes:["Sagging hips","Holding the breath unnecessarily","Hips too high"],alternatives:["dead-bug","side-plank","pallof-press"]}),
make({slug:"side-plank",name:"Side Plank",category:"Core",movementPattern:"Anti-Lateral Flexion",equipment:["Bodyweight"],primaryMuscles:["Obliques"],secondaryMuscles:["Glutes","Shoulders"],difficulty:"Beginner",exerciseType:"Isolation",description:"An isometric exercise for the side of the trunk and lateral hip stabilizers.",instructions:["Support yourself on one forearm or hand with your body stacked side-on.","Lift the hips and create a straight line from head to feet.","Hold while breathing under control, then switch sides."],tips:["Keep the hips high and stacked.","Use a bent-knee version to scale the exercise."],commonMistakes:["Rotating the torso","Letting the hips drop","Holding the breath"],alternatives:["plank","dead-bug","pallof-press"]}),
make({slug:"dead-bug",name:"Dead Bug",category:"Core",movementPattern:"Anti-Extension",equipment:["Bodyweight"],primaryMuscles:["Abdominals"],secondaryMuscles:["Hip flexors"],difficulty:"Beginner",exerciseType:"Isolation",description:"A controlled floor exercise for trunk stability while the limbs move independently.",instructions:["Lie on your back with hips and knees bent and arms raised.","Brace the trunk and slowly extend the opposite arm and leg without losing your back position.","Return to the start and alternate sides."],tips:["Move slowly enough to maintain trunk position.","Shorten the range if your lower back lifts."],commonMistakes:["Arching the back","Moving too quickly","Losing breathing control"],alternatives:["plank","bird-dog","pallof-press"]}),
make({slug:"pallof-press",name:"Pallof Press",category:"Core",movementPattern:"Anti-Rotation",equipment:["Cable or resistance band"],primaryMuscles:["Abdominals","Obliques"],secondaryMuscles:["Glutes","Shoulders"],difficulty:"Beginner",exerciseType:"Isolation",description:"An anti-rotation exercise that challenges the trunk to resist a sideways pull.",instructions:["Stand perpendicular to the cable or band and hold the handle at your chest.","Brace and press the handle straight forward without allowing the torso to rotate.","Return the handle to the chest under control and repeat before switching sides."],tips:["Use a stance that lets you resist rotation without leaning.","Move the arms slowly."],commonMistakes:["Rotating toward the cable","Leaning away","Using excessive resistance"],alternatives:["side-plank","dead-bug","cable-woodchop"]}),
make({slug:"kettlebell-swing",name:"Kettlebell Swing",category:"Full Body",movementPattern:"Hinge",equipment:["Kettlebell"],primaryMuscles:["Glutes","Hamstrings"],secondaryMuscles:["Core","Shoulders","Forearms"],difficulty:"Intermediate",exerciseType:"Compound",description:"A ballistic hip-hinge movement for power and conditioning.",instructions:["Start with the kettlebell slightly in front and hike it back between your legs.","Drive the hips forward forcefully to project the kettlebell upward.","Let it swing back between the legs and repeat the hinge without turning it into a squat."],tips:["The hips create the power; the arms guide the bell.","Master the hinge before adding speed or load."],commonMistakes:["Squatting the swing","Lifting with the arms","Rounding the back"],alternatives:["cable-pull-through","romanian-deadlift","goblet-squat"]}),
make({slug:"farmer-carry",name:"Farmer Carry",category:"Full Body",movementPattern:"Carry",equipment:["Dumbbells or kettlebells"],primaryMuscles:["Forearms","Core"],secondaryMuscles:["Traps","Glutes","Legs"],difficulty:"Beginner",exerciseType:"Compound",description:"A loaded carry that builds grip, trunk stability and work capacity.",instructions:["Stand tall with weights at your sides and shoulders controlled.","Walk with short, steady steps while keeping the trunk upright.","Stop before posture and grip quality break down."],tips:["Use a load you can carry without leaning.","Keep the weights close to your sides."],commonMistakes:["Leaning side to side","Shrugging excessively","Unstable steps"],alternatives:["suitcase-carry","deadlift","walking-lunge"]}),
make({slug:"burpee",name:"Burpee",category:"Full Body",movementPattern:"Conditioning",equipment:["Bodyweight"],primaryMuscles:["Full body"],secondaryMuscles:["Chest","Legs","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A bodyweight conditioning movement combining a squat, plank position and stand or jump.",instructions:["From standing, place your hands down and move your feet back to a strong plank.","Return the feet under the body and stand tall, adding a jump if appropriate.","Repeat at a sustainable pace."],tips:["Use a step-back version to reduce impact.","Prioritize consistent movement over speed."],commonMistakes:["Losing plank control","Landing stiffly","Going too fast to maintain form"],alternatives:["mountain-climber","jumping-jack","bodyweight-squat"]}),
make({slug:"mountain-climber",name:"Mountain Climber",category:"Full Body",movementPattern:"Conditioning",equipment:["Bodyweight"],primaryMuscles:["Core"],secondaryMuscles:["Shoulders","Hip flexors","Legs"],difficulty:"Beginner",exerciseType:"Compound",description:"A plank-based conditioning drill with alternating knee drives.",instructions:["Start in a stable high-plank position with hands under the shoulders.","Drive one knee toward the chest while keeping the hips controlled.","Switch legs rhythmically without losing the plank position."],tips:["Keep the shoulders stacked over the hands.","Slow the pace if the hips begin bouncing."],commonMistakes:["Hips rising too high","Hands drifting forward","Rushing with poor control"],alternatives:["burpee","plank","high-knees"]}),
make({slug:"jumping-jack",name:"Jumping Jack",category:"Cardio",movementPattern:"Low-Impact Conditioning",equipment:["Bodyweight"],primaryMuscles:["Full body"],secondaryMuscles:["Calves","Shoulders"],difficulty:"Beginner",exerciseType:"Cardio",description:"A simple rhythmic conditioning exercise that raises heart rate with repeated arm and leg movement.",instructions:["Stand tall with feet together and arms by your sides.","Jump or step the feet outward while raising the arms overhead.","Return to the starting position and repeat rhythmically."],tips:["Use a step-out version for lower impact.","Keep landings soft and controlled."],commonMistakes:["Hard landings","Rushing the movement","Losing rhythm"],alternatives:["burpee","high-knees","mountain-climber"]}),
make({slug:"stationary-bike",name:"Stationary Bike",category:"Cardio",movementPattern:"Cycling",equipment:["Stationary bike"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Hamstrings","Calves"],difficulty:"Beginner",exerciseType:"Cardio",description:"A low-impact cycling option for aerobic conditioning and intervals.",instructions:["Adjust the seat so your leg remains slightly bent at the bottom of the pedal stroke.","Pedal smoothly while maintaining the desired resistance and cadence.","Increase or decrease resistance gradually to match the session goal."],tips:["Set the bike correctly before starting intervals.","Build intensity progressively."],commonMistakes:["Poor seat height","Starting too hard","Using resistance that breaks cadence"],alternatives:["rowing-machine","treadmill-walk","elliptical"]}),
make({slug:"treadmill-walk",name:"Treadmill Walk",category:"Cardio",movementPattern:"Walking",equipment:["Treadmill"],primaryMuscles:["Legs"],secondaryMuscles:["Glutes","Calves"],difficulty:"Beginner",exerciseType:"Cardio",description:"A simple aerobic exercise that can be scaled through speed and incline.",instructions:["Set a comfortable walking speed and step onto the belt safely.","Walk with an upright posture and natural arm movement.","Adjust speed or incline gradually to reach the desired effort."],tips:["Use the handrails only when needed for safety.","Increase intensity gradually."],commonMistakes:["Holding the rails throughout","Leaning forward","Increasing intensity too quickly"],alternatives:["stationary-bike","elliptical","walking"]}),
make({slug:"bodyweight-squat",name:"Bodyweight Squat",category:"Bodyweight",movementPattern:"Squat",equipment:["Bodyweight"],primaryMuscles:["Quads","Glutes"],secondaryMuscles:["Core","Adductors"],difficulty:"Beginner",exerciseType:"Compound",description:"A fundamental squat pattern for learning lower-body mechanics and general fitness.",instructions:["Stand with feet in a comfortable stance and brace your trunk.","Bend the knees and hips to lower under control while keeping the feet planted.","Drive through the floor to stand tall."],tips:["Use a box or bench as a depth target while learning.","Keep pressure across the whole foot."],commonMistakes:["Heels lifting","Knees collapsing inward","Dropping quickly"],alternatives:["goblet-squat","back-squat","split-squat"]}),
make({slug:"inverted-row",name:"Inverted Row",category:"Bodyweight",movementPattern:"Horizontal Pull",equipment:["Bar or suspension trainer"],primaryMuscles:["Upper back","Lats"],secondaryMuscles:["Biceps","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A bodyweight horizontal pull that can be scaled by changing body angle.",instructions:["Set a secure bar around waist or chest height and position your body underneath it.","Pull your chest toward the bar while keeping your body in a straight line.","Lower under control until your arms are extended."],tips:["Raise the bar or bend the knees to make the movement easier.","Keep the hips from sagging."],commonMistakes:["Sagging hips","Pulling only with the arms","Using an insecure setup"],alternatives:["pull-up","lat-pulldown","seated-cable-row"]}),
make({slug:"incline-push-up",name:"Incline Push-Up",category:"Bodyweight",movementPattern:"Horizontal Push",equipment:["Bodyweight","Bench or box"],primaryMuscles:["Chest"],secondaryMuscles:["Triceps","Front delts","Core"],difficulty:"Beginner",exerciseType:"Compound",description:"A scaled push-up performed with the hands elevated.",instructions:["Place your hands on a stable elevated surface and step into a straight-body position.","Lower your chest toward the surface while keeping the trunk braced.","Press away to return to the start."],tips:["Use a lower surface as you get stronger.","Check that the support is stable before starting."],commonMistakes:["Hips sagging","Hands too narrow","Unstable support"],alternatives:["push-up","knee-push-up","dumbbell-bench-press"]}),
];

export const EXERCISE_CATEGORIES = ["All", ...Array.from(new Set(EXERCISE_DATABASE.map(x => x.category)))];
export const EXERCISE_EQUIPMENT = ["All", ...Array.from(new Set(EXERCISE_DATABASE.flatMap(x => x.equipment))).sort()];

export function getExercise(slug: string) {
  return EXERCISE_DATABASE.find(x => x.slug === slug);
}
