"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import "./community-open.css";

type WorkoutDay={user_id:string;date_key:string;title?:string|null;entries?:unknown;has_photo?:boolean|null;has_video?:boolean|null;updated_at?:string|null};
type Profile={id:string;first_name?:string|null;last_name?:string|null;created_at?:string|null};

function displayName(p?:Profile){const f=String(p?.first_name??"").trim();const l=String(p?.last_name??"").trim();if(!f)return "Gym Log Member";return l?`${f} ${l[0].toUpperCase()}.`:f;}
function avatarLetter(p?:Profile){const n=displayName(p);return n==="Gym Log Member"?"G":n[0].toUpperCase();}
function dateKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function memberSince(v?:string|null){if(!v)return "Member";const d=new Date(v);if(Number.isNaN(d.getTime()))return "Member";const n=new Date();let m=(n.getFullYear()-d.getFullYear())*12+n.getMonth()-d.getMonth();if(n.getDate()<d.getDate())m--;if(m<1)return "New member";if(m<12)return `${m} month${m===1?"":"s"} member`;const y=Math.floor(m/12),r=m%12;return `${y} year${y===1?"":"s"}${r?` ${r} mo`:""} member`;}
function description(w:WorkoutDay){const e=Array.isArray(w.entries)?w.entries[0] as any:null;const raw=String(e?.notes??"").trim();if(!raw)return "";const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const title=String(w.title??"").trim().toLowerCase();const useful=lines.filter(x=>x.toLowerCase()!==title&&!/^[-+•]/.test(x));return useful[0]??lines[0]??"";}

export default function CommunityOpen(){
 const today=useMemo(dateKey,[]);const [selectedDate,setSelectedDate]=useState(today);const [workouts,setWorkouts]=useState<WorkoutDay[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [counts,setCounts]=useState<Record<string,number>>({});const [loading,setLoading]=useState(true);const [signedIn,setSignedIn]=useState(false);const [message,setMessage]=useState("");const [expanded,setExpanded]=useState<string|null>(null);const [picker,setPicker]=useState(false);const isToday=selectedDate===today;
 async function loadProfiles(ids:string[]){if(!ids.length){setProfiles({});setCounts({});return;}const p=await supabase.from("profiles").select("id, first_name, last_name, created_at").in("id",ids);const map:Record<string,Profile>={};(p.data??[]).forEach(x=>{map[x.id]=x as Profile;});setProfiles(map);const c:Record<string,number>={};await Promise.all(ids.map(async id=>{const r=await supabase.from("workout_days").select("date_key",{count:"exact",head:true}).eq("user_id",id);c[id]=r.count??0;}));setCounts(c);}
 async function load(day:string){setLoading(true);setMessage("");setExpanded(null);const {data}=await supabase.auth.getSession();const uid=data.session?.user?.id;setSignedIn(Boolean(uid));if(!uid){setWorkouts([]);setProfiles({});setCounts({});setLoading(false);setMessage("Sign in to join the Gym Log community.");return;}const r=await supabase.from("workout_days").select("user_id, date_key, title, entries, has_photo, has_video, updated_at").eq("date_key",day).order("updated_at",{ascending:false});if(r.error){setWorkouts([]);setProfiles({});setCounts({});setLoading(false);setMessage("Community workouts are unavailable right now.");return;}const rows=(r.data??[]) as WorkoutDay[];setWorkouts(rows);await loadProfiles(Array.from(new Set(rows.map(x=>x.user_id).filter(Boolean))));setLoading(false);}
 useEffect(()=>{load(selectedDate);},[selectedDate]);
 const label=new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});
 return <main className="community-open-page"><div className="community-open-shell"><header className="community-open-header"><div><p className="community-eyebrow">GYM LOG COMMUNITY</p><h1>Community</h1><p className="community-open-subtitle">See what the Gym Log community is training on any day.</p></div><div className="community-date-control"><button type="button" className="community-today-pill" aria-expanded={picker} onClick={()=>setPicker(x=>!x)}>{isToday?"TODAY":label}</button>{picker&&<div className="community-date-picker"><label htmlFor="community-date">Choose a date</label><input id="community-date" type="date" value={selectedDate} onChange={e=>{if(e.target.value){setSelectedDate(e.target.value);setPicker(false);}}}/>{!isToday&&<button type="button" className="community-date-reset" onClick={()=>{setSelectedDate(today);setPicker(false);}}>Back to today</button>}</div>}</div></header>
 {message&&<div className="community-open-message" role="status">{message}</div>}
 <section className="community-feed-section"><div className="community-feed-heading"><div><h2>{isToday?"Training today":`Training on ${label}`}</h2><p>{loading?"Loading the community feed…":`${workouts.length} workout${workouts.length===1?"":"s"} logged`}</p></div>{!loading&&workouts.length>0&&<span className="community-count">{workouts.length}</span>}</div>
 {!signedIn&&!loading?<div className="community-empty"><div className="community-empty-icon">◎</div><h3>Join the community</h3><p>Sign in to see what other Gym Log members are training.</p></div>:loading?<div className="community-loading-card"><span className="community-spinner"/>Loading community workouts</div>:workouts.length===0?<div className="community-empty"><div className="community-empty-icon">+</div><h3>No workouts logged</h3><p>No community workouts have been logged for this date.</p></div>:<div className="community-feed-list">{workouts.map(w=>{const p=profiles[w.user_id];const title=String(w.title??"Workout").trim()||"Workout";const key=`${w.user_id}-${w.date_key}`;const open=expanded===key;const desc=description(w);const total=counts[w.user_id]??0;return <article className={`community-workout-card${open?" expanded":""}`} key={key}><button type="button" className="community-workout-trigger" aria-expanded={open} onClick={()=>setExpanded(open?null:key)}><div className="community-workout-person"><div className="community-avatar" aria-hidden="true">{avatarLetter(p)}</div><div className="community-person-copy"><strong>{displayName(p)}</strong><span>{memberSince(p?.created_at)} · {total} workout{total===1?"":"s"} logged</span></div><div className="community-feed-indicators">{w.has_photo&&<span title="Photo logged" aria-label="Photo logged">▣</span>}{w.has_video&&<span title="Video logged" aria-label="Video logged">▶</span>}</div></div><div className="community-workout-summary"><h3>{title}</h3></div></button>{open&&<div className="community-workout-details"><div className="community-detail-row"><span className="community-detail-label">Description</span><p>{desc||"No workout description added."}</p></div>{(w.has_photo||w.has_video)&&<div className="community-media-row">{w.has_photo&&<span>▣ Photo logged</span>}{w.has_video&&<span>▶ Video logged</span>}</div>}</div>}</article>})}</div>}
 </section></div></main>;
}
