import type { ProgramWorkout } from "./programWorkouts";

type SpecificProgram = { workouts: ProgramWorkout[]; progression: string; accuracyNote: string };
const gym=(days:[string,string,string[]][]):ProgramWorkout[]=>days.map(([day,focus,exercises])=>({day,focus,exercises,guidance:"Gym Log original template. Adjust sets, reps, loading and recovery to your experience; this is not an official prescription."}));

export const SPECIFIC_PROGRAMS_8:Record<string,SpecificProgram>={
  "dup-powerlifting":{workouts:gym([["Day 1","Squat volume",["Back Squat","Bench Press","Romanian Deadlift","Row","Ab Wheel"]],["Day 2","Bench volume",["Bench Press","Overhead Press","Lat Pulldown","Split Squat","Triceps Pressdown"]],["Day 3","Deadlift intensity",["Deadlift","Paused Squat","Incline Bench Press","Chest-Supported Row","Hamstring Curl"]],["Day 4","Bench intensity",["Bench Press","Front Squat","Barbell Row","Hip Thrust","Lateral Raise"]]]),progression:"Use daily or weekly undulating changes in intensity and volume, with planned overload and periodic easier training weeks.",accuracyNote:"Gym Log provides an original DUP-style powerlifting structure rather than an official prescription."},
  "3-day-ppl":{workouts:gym([["Day 1","Push",["Bench Press","Overhead Press","Incline Dumbbell Press","Lateral Raise","Triceps Pressdown"]],["Day 2","Pull",["Pull-Up or Lat Pulldown","Barbell Row","Seated Cable Row","Dumbbell Curl","Face Pull"]],["Day 3","Legs",["Back Squat","Romanian Deadlift","Leg Press","Leg Curl","Calf Raise"]]]),progression:"Add reps or load gradually while keeping technique consistent and recovering between sessions.",accuracyNote:"Gym Log original 3-day PPL template, not an official branded prescription."},
  "4-day-ppl":{workouts:gym([["Day 1","Push",["Bench Press","Incline Dumbbell Press","Overhead Press","Lateral Raise","Triceps Pressdown"]],["Day 2","Pull",["Pull-Up","Barbell Row","Lat Pulldown","Preacher Curl","Face Pull"]],["Day 3","Legs",["Back Squat","Romanian Deadlift","Leg Press","Leg Curl","Calf Raise"]],["Day 4","Upper emphasis",["Incline Bench Press","Chest-Supported Row","Machine Press","Cable Row","Arms"]]]),progression:"Progress major movements first, then add accessory reps or load as recovery allows.",accuracyNote:"Gym Log original 4-day PPL-inspired template, not an official prescription."},
  "3-day-full-body-strength":{workouts:gym([["Day 1","Full body strength",["Back Squat","Bench Press","Barbell Row","Romanian Deadlift","Plank"]],["Day 2","Full body strength",["Deadlift","Overhead Press","Pull-Up","Bulgarian Split Squat","Curl"]],["Day 3","Full body strength",["Front Squat","Incline Bench Press","Seated Cable Row","Hip Thrust","Ab Wheel"]]]),progression:"Use repeatable compound movements and gradually increase training load while managing fatigue.",accuracyNote:"Gym Log original full-body strength template."},
  "4-day-full-body-strength":{workouts:gym([["Day 1","Squat emphasis",["Back Squat","Bench Press","Barbell Row","Leg Curl","Plank"]],["Day 2","Hinge emphasis",["Deadlift","Overhead Press","Pull-Up","Split Squat","Curl"]],["Day 3","Press emphasis",["Bench Press","Front Squat","Chest-Supported Row","Romanian Deadlift","Lateral Raise"]],["Day 4","Volume emphasis",["Hack Squat","Incline Bench Press","Lat Pulldown","Hip Thrust","Triceps Pressdown"]]]),progression:"Alternate emphasis across the week and build volume or load gradually without sacrificing recovery.",accuracyNote:"Gym Log original full-body strength template."},
  "minimalist-strength-3-day":{workouts:gym([["Day 1","Strength A",["Squat","Bench Press","Row"]],["Day 2","Strength B",["Deadlift","Overhead Press","Pull-Up"]],["Day 3","Strength C",["Front Squat","Incline Bench Press","Romanian Deadlift"]]]),progression:"Keep exercise selection stable and prioritize steady progress on the small number of key movements.",accuracyNote:"Gym Log original minimalist strength template."},
  "home-dumbbell-4-day":{workouts:gym([["Day 1","Upper A",["Dumbbell Bench Press","One-Arm Row","Shoulder Press","Curl","Triceps Extension"]],["Day 2","Lower A",["Goblet Squat","Dumbbell RDL","Reverse Lunge","Calf Raise","Plank"]],["Day 3","Upper B",["Dumbbell Floor Press","Dumbbell Row","Lateral Raise","Hammer Curl","Push-Up"]],["Day 4","Lower B",["Bulgarian Split Squat","Dumbbell Hip Thrust","Step-Up","Single-Leg RDL","Dead Bug"]]]),progression:"Progress by adding controlled reps, load or range of motion while maintaining good technique.",accuracyNote:"Gym Log original home dumbbell template."},
  "kettlebell-strength-4-day":{workouts:gym([["Day 1","Hinge + press",["Kettlebell Swing","Clean and Press","Goblet Squat","Row","Carry"]],["Day 2","Strength + conditioning",["Turkish Get-Up","Front Rack Squat","One-Arm Press","Swing","Farmer Carry"]],["Day 3","Hinge + pull",["Deadlift Pattern","Kettlebell Row","Reverse Lunge","Clean","Plank"]],["Day 4","Full body",["Clean and Press","Goblet Squat","Swing","Push-Up","Suitcase Carry"]]]),progression:"Build technique and work capacity first, then gradually increase repetitions, load or density.",accuracyNote:"Gym Log original kettlebell strength template."},
  "athletic-strength-3-day":{workouts:gym([["Day 1","Lower strength + power",["Back Squat","Jump Variation","Romanian Deadlift","Split Squat","Core"]],["Day 2","Upper strength + power",["Bench Press","Medicine Ball Throw","Pull-Up","Overhead Press","Row"]],["Day 3","Full body athletic",["Trap Bar Deadlift","Jump Variation","Incline Bench Press","Carry","Anti-Rotation Core"]]]),progression:"Prioritize quality power work, then build strength and conditioning while keeping fatigue appropriate for sport or activity.",accuracyNote:"Gym Log original athletic strength template, not a sport-specific coaching prescription."},
  "hypertrophy-upper-lower-3-day":{workouts:gym([["Day 1","Upper",["Bench Press","Lat Pulldown","Incline Dumbbell Press","Cable Row","Lateral Raise","Curl"]],["Day 2","Lower",["Squat","Romanian Deadlift","Leg Press","Leg Curl","Calf Raise"]],["Day 3","Upper + lower",["Overhead Press","Chest-Supported Row","Hack Squat","Hip Thrust","Lateral Raise","Triceps Pressdown"]]]),progression:"Increase reps or load over time while keeping weekly volume recoverable and effort consistent.",accuracyNote:"Gym Log original 3-day hypertrophy split."},
  "hypertrophy-upper-lower-5-day":{workouts:gym([["Day 1","Upper push",["Bench Press","Incline Dumbbell Press","Lateral Raise","Triceps Pressdown"]],["Day 2","Lower quad",["Squat","Leg Press","Leg Extension","Calf Raise"]],["Day 3","Upper pull",["Pull-Up","Chest-Supported Row","Lat Pulldown","Curl","Face Pull"]],["Day 4","Lower posterior",["Romanian Deadlift","Hip Thrust","Leg Curl","Split Squat","Calf Raise"]],["Day 5","Upper mixed",["Incline Bench Press","Cable Row","Machine Press","Lateral Raise","Arms"]]]),progression:"Build performance across repeated movement patterns while adjusting volume to recovery and training age.",accuracyNote:"Gym Log original 5-day hypertrophy template."},
  "full-body-2-day-strength":{workouts:gym([["Day 1","Full body A",["Squat","Bench Press","Barbell Row","Romanian Deadlift","Plank"]],["Day 2","Full body B",["Deadlift","Overhead Press","Pull-Up","Split Squat","Curl"]]]),progression:"Keep sessions focused and use gradual overload; the lower frequency makes recovery and exercise quality especially important.",accuracyNote:"Gym Log original 2-day full-body strength template."}
};
