"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./tools.module.css";

import { tools } from "./tools-data";
import { PersistentRestTimer, PersistentStopwatch, PersistentIntervalTimer } from "../components/ThemeControl";

const round = (n:number) => Math.round(n*10)/10;

function Header(){return <header className="top-bar"><Link href="/launcher" className="brand" aria-label="Open Gym Log home"><img src="/icons/gym-app-logo-color-40x40.png" alt="Gym Log" className="brand-logo" width={28} height={28}/><h1>Gym Log</h1></Link><Link href="/tools" className="icon-btn" aria-label="All tools" title="All tools">☷</Link></header>}
function Field({label,value,onChange,suffix,min=0,step="any"}:{label:string;value:string;onChange:(v:string)=>void;suffix?:string;min?:number;step?:string}){return <label className={styles.field}><span>{label}</span><div className={styles.inputWrap}><input type="number" inputMode="decimal" min={min} step={step} value={value} onChange={e=>onChange(e.target.value)}/>{suffix&&<em>{suffix}</em>}</div></label>}
function Result({label,value}:{label:string;value:string}){return <div className={styles.result}><span>{label}</span><strong>{value}</strong></div>}
function Note({children}:{children:React.ReactNode}){return <p className={styles.note}>{children}</p>}
function Card({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <><Header/><main className={styles.page}><Link href="/tools" className={styles.back}>← All tools</Link><section className={styles.card}><h2>{title}</h2><p className={styles.subtitle}>{subtitle}</p>{children}</section></main></>}

function OneRM(){const[w,setW]=useState("225"),[r,setR]=useState("5");const max=Number(w)>0&&Number(r)>0&&Number(r)<=20?Number(w)*(1+Number(r)/30):0;return <Card title="1 Rep Max Calculator" subtitle="Estimate your 1RM from a recent set using the Epley formula."><div className={styles.formGrid}><Field label="Weight" value={w} onChange={setW} suffix="lb"/><Field label="Reps" value={r} onChange={setR} min={1} step="1"/></div><Result label="Estimated 1RM" value={max?round(max)+" lb":"—"}/><div className={styles.percentGrid}>{[50,60,65,70,75,80,85,90,95,100].map(p=><div key={p}><b>{p}%</b><span>{max?round(max*p/100)+" lb":"—"}</span></div>)}</div><Note>Training estimates vary. This is not a guarantee of a true one-rep max.</Note></Card>}

function Plates(){const[t,setT]=useState("225"),[b,setB]=useState("45"),[unit,setUnit]=useState<"lb"|"kg">("lb");const ps=unit==="lb"?[45,35,25,10,5,2.5]:[20,15,10,5,2.5,1.25];let x=(Number(t)-Number(b))/2;const used:number[]=[];if(x>=0)for(const p of ps)while(x>=p-.0001){used.push(p);x=round(x-p)}const exact=Math.abs(x)<.01;return <Card title="Plate Calculator" subtitle="Find the plates needed on each side for your target weight."><div className={styles.formGrid}><Field label="Target weight" value={t} onChange={setT} suffix={unit}/><Field label="Bar weight" value={b} onChange={setB} suffix={unit}/></div><div className={styles.toggle}><button className={unit==="lb"?styles.active:""} onClick={()=>setUnit("lb")}>lb</button><button className={unit==="kg"?styles.active:""} onClick={()=>setUnit("kg")}>kg</button></div><Result label="Each side" value={Number(t)>=Number(b)&&exact?(used.length?used.join(" + ")+" "+unit:"Bar only"):"No exact combination"}/><Note>Uses common plate sizes and does not include collars.</Note></Card>}

function Rest(){const[s,setS]=useState(90),[left,setLeft]=useState(90),[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setLeft(v=>{if(v<=1){setRun(false);return 0}return v-1}),1000);return()=>clearInterval(id)},[run]);const preset=(v:number)=>{setS(v);setLeft(v);setRun(false)};return <Card title="Rest Timer" subtitle="Keep your rest periods consistent between sets."><div className={styles.timer}>{String(Math.floor(left/60)).padStart(2,"0")}:{String(left%60).padStart(2,"0")}</div><div className={styles.presetRow}>{[30,60,90,120,180,300].map(v=><button key={v} onClick={()=>preset(v)}>{v<60?v+"s":v/60+"m"}</button>)}</div><div className={styles.actions}><button className={styles.primary} onClick={()=>{if(left===0)setLeft(s);setRun(v=>!v)}}>{run?"Pause":left===0?"Restart":"Start"}</button><button onClick={()=>{setLeft(s);setRun(false)}}>Reset</button></div></Card>}

function Stopwatch(){const[run,setRun]=useState(false),[ms,setMs]=useState(0),[laps,setLaps]=useState<number[]>([]);useEffect(()=>{if(!run)return;const started=performance.now()-ms;const id=setInterval(()=>setMs(performance.now()-started),50);return()=>clearInterval(id)},[run]);const sec=ms/1000;return <Card title="Workout Stopwatch" subtitle="Track total workout time and record laps."><div className={styles.timer}>{Math.floor(sec/60).toString().padStart(2,"0")}:{Math.floor(sec%60).toString().padStart(2,"0")}</div><div className={styles.actions}><button className={styles.primary} onClick={()=>setRun(v=>!v)}>{run?"Pause":"Start"}</button><button onClick={()=>run&&setLaps(v=>[...v,sec])}>Lap</button><button onClick={()=>{setRun(false);setMs(0);setLaps([])}}>Reset</button></div>{laps.length>0&&<div className={styles.laps}>{laps.map((v,i)=><div key={i}><span>Lap {i+1}</span><b>{Math.floor(v/60)}:{String(Math.floor(v%60)).padStart(2,"0")}</b></div>)}</div>}</Card>}

function TDEE(){const[sex,setSex]=useState("male"),[age,setAge]=useState("30"),[h,setH]=useState("70"),[w,setW]=useState("200"),[a,setA]=useState("1.55");const kg=Number(w)/2.20462,cm=Number(h)*2.54,bmr=sex==="male"?10*kg+6.25*cm-5*Number(age)+5:10*kg+6.25*cm-5*Number(age)-161,tdee=bmr*Number(a);return <Card title="TDEE Calculator" subtitle="Estimate daily calorie needs from BMR and activity."><div className={styles.toggle}><button className={sex==="male"?styles.active:""} onClick={()=>setSex("male")}>Male</button><button className={sex==="female"?styles.active:""} onClick={()=>setSex("female")}>Female</button></div><div className={styles.formGrid}><Field label="Age" value={age} onChange={setAge} min={1} step="1" suffix="years"/><Field label="Height" value={h} onChange={setH} min={1} suffix="in"/><Field label="Weight" value={w} onChange={setW} min={1} suffix="lb"/></div><label className={styles.field}><span>Activity</span><select value={a} onChange={e=>setA(e.target.value)}><option value="1.2">Sedentary</option><option value="1.375">Lightly active</option><option value="1.55">Moderately active</option><option value="1.725">Very active</option><option value="1.9">Extremely active</option></select></label><Result label="Estimated TDEE" value={tdee>0?Math.round(tdee).toLocaleString()+" kcal/day":"—"}/><Note>Individual calorie needs can differ. Use this as a starting estimate.</Note></Card>}

function Macros(){const[c,setC]=useState("2500"),[p,setP]=useState("180"),[f,setF]=useState("70");const carbs=Math.max(0,(Number(c)-Number(p)*4-Number(f)*9)/4);return <Card title="Macro Calculator" subtitle="Turn a daily calorie target into protein, carb and fat targets."><div className={styles.formGrid}><Field label="Calories" value={c} onChange={setC} min={1} suffix="kcal"/><Field label="Protein" value={p} onChange={setP} min={0} suffix="g"/><Field label="Fat" value={f} onChange={setF} min={0} suffix="g"/></div><div className={styles.macroGrid}><Result label="Protein" value={Math.round(Number(p))+" g"}/><Result label="Carbs" value={Math.round(carbs)+" g"}/><Result label="Fat" value={Math.round(Number(f))+" g"}/></div><Note>Carbs are the remaining calories after protein and fat.</Note></Card>}

function Warmup(){const[w,setW]=useState("225"),n=Number(w),sets=n>0?[.4,.6,.75,.85].map((x,i)=>[Math.round(n*x),[10,5,3,1][i]]):[];return <Card title="Warm-Up Set Calculator" subtitle="Build a simple ramp-up sequence before your working sets."><Field label="Working weight" value={w} onChange={setW} min={1} suffix="lb"/><div className={styles.laps}>{sets.map((s,i)=><div key={i}><span>Warm-up {i+1} · {s[1]} reps</span><b>{s[0]} lb</b></div>)}<div><span>Working sets</span><b>{n>0?n+" lb":"—"}</b></div></div><Note>Adjust the number of warm-up sets based on the lift and how heavy the working sets are.</Note></Card>}

function BMI(){const[u,setU]=useState("imperial"),[h,setH]=useState("70"),[w,setW]=useState("200"),bmi=u==="imperial"?703*Number(w)/(Number(h)**2):Number(w)/((Number(h)/100)**2),cat=bmi<18.5?"Underweight":bmi<25?"Healthy range":bmi<30?"Overweight":"Obesity";return <Card title="BMI Calculator" subtitle="Calculate body mass index from height and weight."><div className={styles.toggle}><button className={u==="imperial"?styles.active:""} onClick={()=>setU("imperial")}>Imperial</button><button className={u==="metric"?styles.active:""} onClick={()=>setU("metric")}>Metric</button></div><div className={styles.formGrid}><Field label="Height" value={h} onChange={setH} min={1} suffix={u==="imperial"?"in":"cm"}/><Field label="Weight" value={w} onChange={setW} min={1} suffix={u==="imperial"?"lb":"kg"}/></div><Result label="BMI" value={bmi>0?round(bmi).toString():"—"}/><p className={styles.category}>{bmi>0?cat:"Enter your measurements"}</p><Note>BMI is a screening measure and does not distinguish muscle from body fat.</Note></Card>}

function Convert(){const[v,setV]=useState("225"),[from,setFrom]=useState("lb"),n=Number(v),out=from==="lb"?n/2.2046226218:n*2.2046226218;return <Card title="Weight Converter" subtitle="Quickly convert lifting weights between pounds and kilograms."><Field label={"Weight ("+from+")"} value={v} onChange={setV} min={0} suffix={from}/><div className={styles.toggle}><button className={from==="lb"?styles.active:""} onClick={()=>setFrom("lb")}>lb → kg</button><button className={from==="kg"?styles.active:""} onClick={()=>setFrom("kg")}>kg → lb</button></div><Result label="Converted weight" value={n>=0?round(out)+" "+(from==="lb"?"kg":"lb"):"—"}/></Card>}

function Interval(){const[w,setW]=useState("40"),[r,setR]=useState("20"),[rounds,setRounds]=useState("8"),[phase,setPhase]=useState("work"),[left,setLeft]=useState(40),[current,setCurrent]=useState(1),[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setLeft(v=>{if(v>1)return v-1;if(phase==="work"){if(Number(r)>0){setPhase("rest");return Number(r)}setCurrent(x=>x+1);return Number(w)}if(current>=Number(rounds)){setRun(false);return 0}setPhase("work");setCurrent(x=>x+1);return Number(w)}),1000);return()=>clearInterval(id)},[run,phase,r,w,current,rounds]);const reset=()=>{setRun(false);setPhase("work");setCurrent(1);setLeft(Number(w)||1)};return <Card title="Interval Timer" subtitle="Set work, rest and rounds for circuits or conditioning."><div className={styles.formGrid}><Field label="Work" value={w} onChange={v=>{setW(v);if(!run)setLeft(Number(v)||1)}} min={1} step="1" suffix="sec"/><Field label="Rest" value={r} onChange={setR} min={0} step="1" suffix="sec"/><Field label="Rounds" value={rounds} onChange={setRounds} min={1} step="1"/></div><div className={styles.intervalPhase}>{run?(phase==="work"?"WORK":"REST"):"READY"}<strong>{String(Math.max(0,left)).padStart(2,"0")}</strong><span>Round {Math.min(current,Number(rounds))} / {rounds}</span></div><div className={styles.actions}><button className={styles.primary} onClick={()=>setRun(v=>!v)}>{run?"Pause":"Start"}</button><button onClick={reset}>Reset</button></div></Card>}

export function ToolsHub(){const groups=["Strength","Workout","Nutrition","Conversions"];return <><Header/><main className={styles.page}><div className={styles.hero}><span className={styles.kicker}>GYM LOG TOOLS</span><h2>Simple tools for better training.</h2><p>Quick calculators, timers and training utilities built for the gym. No account required.</p></div>{groups.map(g=><section className={styles.group} key={g}><h3>{g}</h3><div className={styles.toolGrid}>{tools.filter(t=>t[3]===g).map(t=><Link href={"/tools/"+t[0]} className={styles.toolCard} key={t[0]}><span className={styles.toolArrow}>↗</span><h4>{t[1]}</h4><p>{t[2]}</p></Link>)}</div></section>)}</main></>}

export function ToolPage({slug}:{slug:string}){const map:Record<string,()=>React.ReactNode>={"one-rep-max-calculator":OneRM,"plate-calculator":Plates,"rest-timer":PersistentRestTimer,"workout-stopwatch":PersistentStopwatch,"tdee-calculator":TDEE,"macro-calculator":Macros,"warm-up-calculator":Warmup,"bmi-calculator":BMI,"weight-converter":Convert,"interval-timer":PersistentIntervalTimer};const C=map[slug];return C?<C/>:<><Header/><main className={styles.page}><section className={styles.card}><h2>Tool not found</h2><Link href="/tools" className={styles.back}>Back to tools</Link></section></main></>}

export { tools };
