export const tools = [
  ["one-rep-max-calculator","1 Rep Max Calculator","Estimate your one-rep max and common training percentages.","Strength"],
  ["plate-calculator","Plate Calculator","Find the plates needed on each side of the bar.","Strength"],
  ["rest-timer","Rest Timer","A simple countdown for between sets.","Workout"],
  ["workout-stopwatch","Workout Stopwatch","Track total workout time and laps.","Workout"],
  ["tdee-calculator","TDEE Calculator","Estimate daily calorie needs from body size and activity.","Nutrition"],
  ["macro-calculator","Macro Calculator","Set protein, carb and fat targets from calories.","Nutrition"],
  ["warm-up-calculator","Warm-Up Set Calculator","Build a practical warm-up sequence from working weight.","Strength"],
  ["volume-calculator","Volume Calculator","Calculate total training volume from sets, reps and weight.","Strength"],
  ["bmi-calculator","BMI Calculator","Calculate BMI from height and weight.","Nutrition"],
  ["weight-converter","Weight Converter","Convert lifting weights between pounds and kilograms.","Conversions"],
  ["interval-timer","Interval Timer","Run repeated work and rest intervals.","Workout"],
  ["emom-timer","EMOM Timer","Every Minute on the Minute pacing timer.","Workout"],
  ["amrap-timer","AMRAP Timer","Time-cap your AMRAP and track rounds.","Workout"],
  ["training-volume-calculator","Training Volume Calculator","Estimate total sets and reps across a workout.","Strength"],
  ["volume-load-calculator","Volume Load Calculator","Calculate total weight moved from load, reps and sets.","Strength"],
  ["rep-percentage-calculator","Rep Percentage Calculator","Calculate common training weights from your 1RM.","Strength"],
  ["strength-standards-calculator","Strength Standards Calculator","Compare bodyweight-based illustrative strength targets.","Strength"],
  ["powerlifting-score-calculator","Powerlifting Score Calculator","Calculate Wilks and DOTS-style powerlifting scores.","Strength"],
  ["body-fat-calculator","Body Fat Calculator","Estimate body fat using circumference measurements.","Nutrition"],
  ["ideal-weight-calculator","Ideal Weight Calculator","Compare a common height-based reference formula.","Nutrition"],
  ["water-intake-calculator","Water Intake Calculator","Get a simple daily hydration starting point.","Nutrition"]
] as const;
