export const EXERCISES: string[] = [
  "Ab wheel rollout",
  "Ab wheel rollout (kneeling)",
  "Ab wheel rollout (standing)",
  "Accordion crunch",
  "Active hang",
  "Adductor machine",
  "Adductor plank",
  "Air bike",
  "Air squat",
  "Arnold press",
  "Assault bike",
  "Back bridge",
  "Back extension",
  "Back extension (45\u00b0)",
  "Back extension (Roman chair)",
  "Back squat",
  "Band pull-apart",
  "Banded face pull",
  "Banded good morning",
  "Banded lateral walk",
  "Banded pull-apart",
  "Barbell bench press",
  "Barbell bench press (paused)",
  "Barbell bench press (touch-and-go)",
  "Barbell Bulgarian split squat",
  "Barbell curl",
  "Barbell deadlift",
  "Barbell glute bridge",
  "Barbell hip thrust",
  "Barbell overhead press",
  "Barbell row",
  "Battle ropes",
  "Bayesian cable curl",
  "Bear crawl",
  "Bear plank",
  "Behind-the-neck press (barbell)",
  "Bench dip",
  "Bench press (machine)",
  "Bench press (Smith machine)",
  "Bent-over reverse fly (dumbbell)",
  "Bicep curl (dumbbell)",
  "Biceps curl (cable)",
  "Biceps curl (EZ-bar)",
  "Biceps curl (preacher machine)",
  "Bicycle crunch",
  "Bike intervals",
  "Bike sprint",
  "Bird dog",
  "Bird dog row",
  "Box jump",
  "Box squat",
  "Box squat (pause)",
  "Box squat (wide stance)",
  "Box step-down",
  "Box step-up",
  "Boxing (heavy bag)",
  "Broad jump",
  "Bulgarian split squat (dumbbell)",
  "Burpee",
  "Cable cross-over",
  "Cable crunch",
  "Cable curl (rope)",
  "Cable curl (straight bar)",
  "Cable face pull",
  "Cable fly",
  "Cable front raise",
  "Cable kickback",
  "Cable lat pulldown",
  "Cable lateral raise",
  "Cable overhead triceps extension",
  "Cable pallof press",
  "Cable rear delt fly",
  "Cable reverse fly",
  "Cable row (seated)",
  "Cable triceps pushdown",
  "Cable woodchop",
  "Calf raise (donkey)",
  "Calf raise (hack squat machine)",
  "Calf raise (leg press)",
  "Calf raise (seated machine)",
  "Calf raise (seated)",
  "Calf raise (single-leg)",
  "Calf raise (Smith machine)",
  "Calf raise (standing machine)",
  "Calf raise (standing)",
  "Captain's chair leg raise",
  "Carrying (farmer's walk)",
  "Cat-cow",
  "Chest dip",
  "Chest fly (cable)",
  "Chest fly (dumbbell)",
  "Chest fly (machine)",
  "Chest press (plate-loaded)",
  "Chest-supported barbell row",
  "Chest-supported dumbbell row",
  "Chest-supported row (dumbbell)",
  "Chest-supported row (machine)",
  "Chest-supported row (T-bar)",
  "Chest-supported T-bar row",
  "Child's pose",
  "Chin-up",
  "Chin-up (assisted)",
  "Chin-up (close)",
  "Chin-up (neutral)",
  "Clamshell",
  "Clean (hang power)",
  "Clean (hang)",
  "Clean (power)",
  "Clean and jerk",
  "Clean pull",
  "Close-grip bench press",
  "Cobra stretch",
  "Concentration curl",
  "Copenhagen plank",
  "Couch stretch",
  "Cross-body hammer curl",
  "Crunch",
  "Curtsy lunge",
  "Cycling (road)",
  "Cycling (stationary bike)",
  "Dead bug",
  "Dead bug (banded)",
  "Dead hang",
  "Deadlift (blocks)",
  "Deadlift (conventional)",
  "Deadlift (deficit)",
  "Deadlift (paused)",
  "Deadlift (sumo)",
  "Deadlift (trap bar)",
  "Decline barbell bench press",
  "Decline bench press (Smith machine)",
  "Decline dumbbell bench press",
  "Decline dumbbell fly",
  "Decline sit-up",
  "Deficit deadlift",
  "Deficit push-up",
  "Diamond push-up",
  "Dip (assisted)",
  "Dip (parallel bars)",
  "Donkey kick",
  "Double unders",
  "Downward dog",
  "Drag curl",
  "Dumbbell bench press",
  "Dumbbell bench press (neutral grip)",
  "Dumbbell deadlift",
  "Dumbbell fly",
  "Dumbbell front raise",
  "Dumbbell glute bridge",
  "Dumbbell goblet squat",
  "Dumbbell hip thrust",
  "Dumbbell lateral raise",
  "Dumbbell lunge",
  "Dumbbell pullover",
  "Dumbbell rear delt fly",
  "Dumbbell reverse wrist curl",
  "Dumbbell Romanian deadlift",
  "Dumbbell row",
  "Dumbbell shoulder press",
  "Dumbbell shoulder press (standing)",
  "Dumbbell shrug",
  "Dumbbell skull crusher",
  "Dumbbell step-up",
  "Dumbbell triceps kickback",
  "Dumbbell wrist curl",
  "Eccentric pull-up",
  "Eccentric push-up",
  "Elliptical",
  "External rotation (band)",
  "External rotation (cable)",
  "EZ-bar curl",
  "Face pull",
  "Face pull (band)",
  "Face pull (cable)",
  "Farmer's carry (dumbbell)",
  "Farmer's carry (trap bar)",
  "Farmer's walk",
  "Fence climber (step-over)",
  "Fire hydrant",
  "Floor press (barbell)",
  "Floor press (dumbbell)",
  "Flutter kick",
  "Foam rolling (glutes)",
  "Foam rolling (lats)",
  "Foam rolling (quads)",
  "Frog pump",
  "Frog stretch",
  "Front plank",
  "Front rack carry",
  "Front rack carry (kettlebell)",
  "Front raise (plate)",
  "Front squat",
  "Front squat (clean grip)",
  "Front squat (cross-arm)",
  "Front squat (dumbbell)",
  "GHD sit-up",
  "Glute bridge",
  "Glute bridge (barbell)",
  "Glute bridge (single-leg)",
  "Glute bridge march",
  "Glute ham raise (GHR)",
  "Glute kickback (band)",
  "Glute kickback (cable)",
  "Glute kickback (machine)",
  "Goblet split squat",
  "Goblet squat",
  "Good morning (band)",
  "Good morning (barbell)",
  "Good morning (safety bar)",
  "Grasshopper stretch",
  "Hack squat (machine)",
  "Hack squat (plate-loaded)",
  "Hack squat (sled)",
  "Half-kneeling landmine press",
  "Half-kneeling pallof press",
  "Hammer curl (dumbbell)",
  "Hamstring curl (lying machine)",
  "Hamstring curl (seated machine)",
  "Hamstring curl (single-leg)",
  "Hamstring curl (Swiss ball)",
  "Hamstring slide (towel)",
  "Handstand hold",
  "Handstand push-up",
  "Hanging knee raise",
  "Hanging leg raise",
  "High pull (barbell)",
  "High pull (kettlebell)",
  "High row (machine)",
  "Hip abduction (machine)",
  "Hip adduction (machine)",
  "Hip flexor stretch",
  "Hip hinge drill",
  "Hip thrust (barbell)",
  "Hip thrust (dumbbell)",
  "Hip thrust (machine)",
  "Hip thrust (single-leg)",
  "Hip thrust (Smith machine)",
  "Hollow body hold",
  "Hollow rock",
  "Hurdle steps",
  "Hyperextension",
  "Incline barbell bench press",
  "Incline bench press (dumbbell)",
  "Incline bench press (Smith machine)",
  "Incline dumbbell bench press",
  "Incline dumbbell curl",
  "Incline dumbbell fly",
  "Incline push-up",
  "Incline walk",
  "Inverted row",
  "Iso-lateral row (machine)",
  "Jerk (push jerk)",
  "Jerk (split jerk)",
  "JM press",
  "Jump lunge",
  "Jump rope",
  "Jump rope (alternating)",
  "Jump rope (double unders)",
  "Jump rope (single unders)",
  "Jump squat",
  "Jumping jack",
  "Jumping rope (HIIT)",
  "Kettlebell clean",
  "Kettlebell deadlift",
  "Kettlebell goblet squat",
  "Kettlebell press",
  "Kettlebell row",
  "Kettlebell snatch",
  "Kettlebell swing",
  "Kettlebell Turkish get-up",
  "Kickback (cable)",
  "Kipping pull-up",
  "Knee tuck",
  "Knees-to-elbows",
  "Kroc row",
  "L-sit",
  "L-sit hang",
  "Landmine deadlift",
  "Landmine press",
  "Landmine rotation",
  "Landmine row",
  "Landmine squat",
  "Lat pulldown (close grip)",
  "Lat pulldown (neutral grip)",
  "Lat pulldown (rope)",
  "Lat pulldown (single-arm)",
  "Lat pulldown (straight bar)",
  "Lat pulldown (underhand)",
  "Lat pulldown (wide grip)",
  "Lat raise (machine)",
  "Lateral lunge",
  "Lateral raise (cable)",
  "Lateral raise (dumbbell)",
  "Lateral raise (machine)",
  "Lateral step-up",
  "Leg curl (machine)",
  "Leg curl (Nordic)",
  "Leg extension (machine)",
  "Leg extension (machine, pause)",
  "Leg extension (single-leg)",
  "Leg press",
  "Leg press (hack)",
  "Leg press (single-leg)",
  "Leg raise",
  "Leg raise (hanging)",
  "Leg raise (lying)",
  "Low row (cable)",
  "Lunge",
  "Lying triceps extension (EZ-bar)",
  "Macebell swing",
  "Machine chest press",
  "Machine high row",
  "Machine lat pulldown",
  "Machine low row",
  "Machine pullover",
  "Machine row",
  "Machine shoulder press",
  "McGill curl-up",
  "Meadows row",
  "Medicine ball slam",
  "Medicine ball toss",
  "Military press",
  "Mini-band monster walk",
  "Mountain climber",
  "Neck extension",
  "Neck flexion",
  "Neutral-grip pull-up",
  "Nordic hamstring curl",
  "Oblique crunch",
  "Oblique twist",
  "One-arm push-up",
  "One-arm row (cable)",
  "Overhead carry",
  "Overhead carry (barbell)",
  "Overhead carry (kettlebell)",
  "Overhead press (barbell)",
  "Overhead press (dumbbell)",
  "Overhead squat",
  "Overhead triceps extension (cable)",
  "Overhead triceps extension (dumbbell)",
  "Pallof press",
  "Pallof press (kneeling)",
  "Pallof press (standing)",
  "Pause bench press",
  "Pause deadlift",
  "Pause squat",
  "Pec deck fly",
  "Pendlay row",
  "Pigeon stretch",
  "Pike push-up",
  "Pin squat",
  "Pistol squat",
  "Plank",
  "Plank (forearm)",
  "Plank (RKC)",
  "Plank (side)",
  "Plank (side, knees)",
  "Plank (stir-the-pot)",
  "Plank jacks",
  "Plank to push-up",
  "Power clean",
  "Power shrug",
  "Power snatch",
  "Preacher curl (EZ-bar)",
  "Preacher curl (machine)",
  "Prone T raise",
  "Prone W raise",
  "Prone Y raise",
  "Prowler push",
  "Pull-through (cable)",
  "Pull-up",
  "Pull-up (assisted)",
  "Pull-up (close)",
  "Pull-up (neutral)",
  "Pull-up (wide)",
  "Pullover (machine)",
  "Push press",
  "Push-up",
  "Push-up (decline)",
  "Push-up (diamond)",
  "Push-up (incline)",
  "Push-up (wide)",
  "Pushdown (straight bar)",
  "Pushdown (triceps rope)",
  "Quadruped rock back",
  "Quick feet drills",
  "Rack pull",
  "RDL (barbell)",
  "RDL (dumbbell)",
  "Rear delt fly (cable)",
  "Rear delt fly (dumbbell)",
  "Rear delt fly (machine)",
  "Renegade row",
  "Reverse crunch",
  "Reverse curl (barbell)",
  "Reverse fly (cable)",
  "Reverse hyper",
  "Reverse lunge",
  "Reverse lunge (barbell)",
  "Reverse lunge (dumbbell)",
  "Reverse pec deck",
  "Ring dip",
  "Ring push-up",
  "Ring row",
  "Rollout (Swiss ball)",
  "Romanian deadlift",
  "Rope climb",
  "Row (barbell)",
  "Row (cable)",
  "Row (chest-supported machine)",
  "Row (dumbbell)",
  "Row (erg)",
  "Row (plate-loaded)",
  "Row (seated cable)",
  "Row (single-arm cable)",
  "Row (single-arm machine)",
  "Row (TRX)",
  "Row intervals",
  "Rowing (erg)",
  "Run intervals",
  "Running",
  "Russian twist",
  "Safety bar good morning",
  "Safety bar squat",
  "Sandbag carry",
  "Sandbag clean",
  "Sandbag squat",
  "Scapular pull-up",
  "Scapular push-up",
  "Scapular retraction drill",
  "Seal row (barbell)",
  "Seated cable face pull",
  "Seated calf raise",
  "Seated dumbbell curl",
  "Seated dumbbell press",
  "Seated hamstring stretch",
  "Seated leg curl",
  "Seated row (cable)",
  "Shadow boxing",
  "Shoulder dislocates (band)",
  "Shoulder press (Arnold)",
  "Shoulder press (landmine)",
  "Shoulder press (machine)",
  "Shoulder press (plate-loaded)",
  "Shoulder tap",
  "Shrug (barbell)",
  "Shrug (dumbbell)",
  "Shrug (machine)",
  "Shrug (trap bar)",
  "Side lunge",
  "Side plank",
  "Side plank reach-through",
  "Side-lying hip abduction",
  "Single-arm dumbbell row",
  "Single-arm kneeling lat pulldown",
  "Single-arm lat pulldown (cable)",
  "Single-leg deadlift",
  "Single-leg glute bridge",
  "Single-leg hamstring slide",
  "Single-leg Romanian deadlift (barbell)",
  "Sissy squat",
  "Sit-up",
  "Skater jump",
  "Ski erg",
  "Skull crusher (EZ-bar)",
  "Sled drag",
  "Sled pull",
  "Sled push",
  "Sled row",
  "Smith machine bench press",
  "Smith machine hip thrust",
  "Smith machine incline press",
  "Smith machine lunge",
  "Smith machine Romanian deadlift",
  "Smith machine squat",
  "Snatch (hang)",
  "Snatch (power)",
  "Snatch pull",
  "Snatch-grip deadlift",
  "Spanish squat",
  "Spider curl",
  "Spin bike",
  "Split squat",
  "Split squat (barbell)",
  "Split squat (Bulgarian)",
  "Split squat (dumbbell)",
  "Spoto press",
  "Sprint",
  "Squat (bodyweight)",
  "Squat (front)",
  "Squat (goblet)",
  "Squat (safety bar)",
  "Squat (SSB)",
  "Stair climb",
  "Stair climber",
  "Standing cable row",
  "Standing hip abduction (cable)",
  "Step-down",
  "Step-up",
  "Step-up (barbell)",
  "Step-up (kettlebell)",
  "Stepmill",
  "Stiff-leg deadlift",
  "Stir-the-pot (Swiss ball)",
  "Straight-arm pulldown",
  "Straight-arm pulldown (bar)",
  "Straight-arm pulldown (rope)",
  "Suitcase carry",
  "Suitcase carry (kettlebell)",
  "Sumo deadlift",
  "Superman",
  "Superman hold",
  "T-bar row",
  "Table row",
  "Tempo bench press",
  "Tempo deadlift",
  "Tempo squat",
  "Thoracic rotation",
  "Thruster",
  "Tibialis raise",
  "Tibialis raise (band)",
  "Tibialis raise (machine)",
  "Toe raise",
  "Toe touches",
  "Trap bar deadlift",
  "Treadmill run",
  "Treadmill walk",
  "Triceps dip",
  "Triceps dip (bench)",
  "Triceps dip (machine)",
  "Triceps dip (ring)",
  "Triceps extension (cable)",
  "Triceps extension (EZ-bar)",
  "Triceps overhead extension",
  "Triceps pushdown (rope)",
  "Triceps pushdown (V-bar)",
  "Tuck jump",
  "Turkish get-up",
  "Upper body ergometer",
  "Upright row (barbell)",
  "Upright row (cable)",
  "Upward dog",
  "V-sit hold",
  "V-up",
  "Vertical jump",
  "Waiter walk",
  "Walking lunge",
  "Walking lunge (barbell)",
  "Walking lunge (dumbbell)",
  "Wall ball",
  "Wall sit",
  "Wide-grip lat pulldown",
  "Wide-grip pull-up",
  "Windshield wiper",
  "Woodchop (cable)",
  "Wrist curl",
  "Wrist roller",
  "Y-raise (cable)",
  "Y-raise (dumbbell)",
  "Yates row",
  "Yoga flow",
  "Zercher carry",
  "Zercher squat",
  "Zottman curl"
];
